<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan_1</name>
   <tag></tag>
   <elementGuidId>d6c8ad04-e319-4170-b5f5-74dc4bbdc648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='e90Y1y']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Y1y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e38ca6f2-e4b4-45ab-844d-a4e3d2a9ae30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69287411-6bdf-4fc4-8113-f15a8a0ff788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e90Y1y</value>
      <webElementGuid>ae90f480-3deb-47f4-b107-22ae91f34b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-4 ml-4 btn-primary btn-additional-document btn-revise-document-penanganan pull-right z-button</value>
      <webElementGuid>1866cea6-6690-403c-b6d5-b58ea152bee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>a136b268-30a7-4719-82f6-31c7adfad014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Y1y&quot;)</value>
      <webElementGuid>4c2a526c-0dca-4e59-a5a9-f4cb296d38a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='e90Y1y']</value>
      <webElementGuid>2ec247a9-b7ca-4a31-a0cc-287a85924efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e90Y0y']/button</value>
      <webElementGuid>f919bce0-397c-4c1f-a002-ff48ec910ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[7]/following::button[1]</value>
      <webElementGuid>2f2b70fb-97d4-40be-8702-604c71e9c1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[11]/following::button[2]</value>
      <webElementGuid>1c353961-55d7-4f3a-8cd9-967746e9236d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Tindak Lanjut'])[1]/preceding::button[1]</value>
      <webElementGuid>75b695af-39e0-4a07-b40e-125fa14bd02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Tindak Lanjut'])[1]/preceding::button[2]</value>
      <webElementGuid>a712c25d-6cfd-4c05-90ec-b7f6d78da500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/button</value>
      <webElementGuid>71d6cc6a-e01d-48b9-a30b-af6930580818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'e90Y1y' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>0184269a-e61d-4f16-bf40-19dc8ee7671a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
