<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bukti Koordinasi PIC Penanganan ke Konsumen</name>
   <tag></tag>
   <elementGuidId>a929ccde-e1cc-4341-9b23-6986ce17e1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='e90Ynm-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Ynm-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6d843df9-8c78-459a-9f1d-00240502d3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>e90Ynm-real</value>
      <webElementGuid>cb4b4ddc-8477-4219-ba2a-d19085541e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e90Ynm-cnt</value>
      <webElementGuid>1bebbded-7206-420a-9718-49ff2f153b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>f74e7ada-0c63-4cbb-94e3-4e2d09098215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bukti Koordinasi PIC Penanganan ke Konsumen*</value>
      <webElementGuid>0a143276-6844-4cba-9e14-c97d05c4568b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Ynm-cnt&quot;)</value>
      <webElementGuid>f6050a27-3140-4dd2-aa1a-d5274f99c1f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='e90Ynm-cnt']</value>
      <webElementGuid>33d80cb6-a2c0-47b8-9ca1-6e17ecd128bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='e90Ynm']/label</value>
      <webElementGuid>97008852-73db-4b20-8504-fbe7bc0c4d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[3]/following::label[1]</value>
      <webElementGuid>da66d1b4-ac6d-47c6-9a9c-9ec0d81f176a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[5]/following::label[1]</value>
      <webElementGuid>8e74cf04-85c2-4f5b-875a-85cfd2d5c496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[5]/preceding::label[1]</value>
      <webElementGuid>d6b211d9-3c00-4eff-9917-6a14a1d9cd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[5]/preceding::label[1]</value>
      <webElementGuid>b7d47df2-d789-4e15-ae39-3a5a4185606a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bukti Koordinasi PIC Penanganan ke Konsumen*']/parent::*</value>
      <webElementGuid>383d00ef-c097-4d71-8341-ca598f82d761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/span/span/label</value>
      <webElementGuid>b8975457-3057-405c-9356-e6dec76eb15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'e90Ynm-cnt' and (text() = 'Bukti Koordinasi PIC Penanganan ke Konsumen*' or . = 'Bukti Koordinasi PIC Penanganan ke Konsumen*')]</value>
      <webElementGuid>f1cde9bc-0d6c-4440-81d1-0e65f1c8d552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
