<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BAP</name>
   <tag></tag>
   <elementGuidId>ccc2afff-3118-4547-aa4b-8851b3de3eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c2YBj1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YBj1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6e8ad07f-0ccb-4857-a437-9ed61c3a6a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YBj1</value>
      <webElementGuid>422aa96d-205a-42c5-8eec-2051c7ed1875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab z-tab-selected</value>
      <webElementGuid>e8a4855f-e2bd-4330-8413-ad3d5d38e84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAP</value>
      <webElementGuid>ebfc80d4-635f-4cd9-9b0d-dcbf94f3c500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YBj1&quot;)</value>
      <webElementGuid>9fe7a17c-7aa7-4b10-b44b-f38a21f3e14d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2YBj1']</value>
      <webElementGuid>36c00331-413c-4914-9e1c-2fd67d819345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2YBe1-cave']/li[5]</value>
      <webElementGuid>04348a98-bcaa-45a7-a6e2-d4167a2c00a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindak Lanjut'])[1]/following::li[1]</value>
      <webElementGuid>00cdd3d6-897b-43c1-bde1-09ecafed1837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pengaduan'])[1]/following::li[2]</value>
      <webElementGuid>7454cf1d-b982-49ba-a53a-4dd7f64c14be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Pengaduan'])[1]/preceding::li[1]</value>
      <webElementGuid>a2ddd017-eb9f-4b79-9f20-0b714d80b622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[5]</value>
      <webElementGuid>d5de3146-db1a-46be-b5a9-118c04bc39ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2YBj1' and (text() = 'BAP' or . = 'BAP')]</value>
      <webElementGuid>267bf198-1abb-48c8-99bb-965b893ff1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
