<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hasil Pertemuan antara Pelapor dengan _6fa85c</name>
   <tag></tag>
   <elementGuidId>398d37b7-6c8a-4f18-9768-bbd90ca1e7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='c2YB3c0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YB3c0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdaee58c-d693-458f-9747-e23441f6f21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YB3c0</value>
      <webElementGuid>caf372e4-20d0-45e3-a6c0-c45a11623812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>78931d88-595e-4cd1-b3ea-a14f20c2972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasil Pertemuan antara Pelapor dengan Perwakilan Perusahaan</value>
      <webElementGuid>26d59ebf-b9b0-4ca8-b8b7-5daed4e9f078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YB3c0&quot;)</value>
      <webElementGuid>9d37eff1-1764-46b0-8269-be8fea59e072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='c2YB3c0']</value>
      <webElementGuid>4b4c16de-347e-43b2-b797-b1208abc0801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c2YB2c0']/span</value>
      <webElementGuid>6abee2e1-f6c2-471b-afe3-3d851f805121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak sepakat'])[1]/following::span[2]</value>
      <webElementGuid>ba5d5901-8996-4075-96ff-c47bd8487154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Sepakat'])[1]/following::span[3]</value>
      <webElementGuid>384d1659-c7f5-4ebb-ba30-6eb76763c642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Dokumen BAP'])[1]/preceding::span[2]</value>
      <webElementGuid>8bc59f6b-e5ca-4be8-9b44-e2041c85bb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::span[3]</value>
      <webElementGuid>2fe96de6-c5be-427c-b673-d6f934cca05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hasil Pertemuan antara Pelapor dengan Perwakilan Perusahaan']/parent::*</value>
      <webElementGuid>75c667b2-6dca-4a5b-9bc0-0e3ffc7da539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span</value>
      <webElementGuid>98584430-2fcb-4851-9c47-ebc39a5a0ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'c2YB3c0' and (text() = 'Hasil Pertemuan antara Pelapor dengan Perwakilan Perusahaan' or . = 'Hasil Pertemuan antara Pelapor dengan Perwakilan Perusahaan')]</value>
      <webElementGuid>0c622e10-1afa-40bf-b6c5-e51565b0e866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
