<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dokumen</name>
   <tag></tag>
   <elementGuidId>9e604ca9-c874-4533-98e2-ddb4aa5769c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='e90Yg1-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Yg1-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e489fcd2-01cf-4b14-abbc-fcd907699bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e90Yg1-cnt</value>
      <webElementGuid>ae34b861-072e-49ad-8d4a-e8d90cc2d562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>800571f5-d650-4648-a5d3-ceaf6a5bc657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen</value>
      <webElementGuid>44684d91-1d6d-4eb6-9007-43b754163f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Yg1-cnt&quot;)</value>
      <webElementGuid>950f57b1-47de-4eec-999b-68d6f6b743e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e90Yg1-cnt']</value>
      <webElementGuid>60a17b4d-55b6-4ac1-93c9-994b8002c2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e90Yg1-cave']/span</value>
      <webElementGuid>b6162861-10c0-4110-804b-c5ace4c658e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulir'])[1]/following::span[1]</value>
      <webElementGuid>32727234-bc8f-4763-81c2-4d4b3897b350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::span[2]</value>
      <webElementGuid>3be35c7d-8110-4fce-a864-5438895cec6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pengaduan'])[1]/preceding::span[1]</value>
      <webElementGuid>98961334-4768-4ba7-8997-ef1d1fea6c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindak Lanjut'])[1]/preceding::span[2]</value>
      <webElementGuid>a14f7da3-e71a-4469-8cf5-1dcb92ee3355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dokumen']/parent::*</value>
      <webElementGuid>47090368-3b50-424c-b130-1618feffa765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/span</value>
      <webElementGuid>4e2e1275-576a-4c19-a093-e55fca05662e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e90Yg1-cnt' and (text() = 'Dokumen' or . = 'Dokumen')]</value>
      <webElementGuid>853e835b-e203-4cdb-b1af-35315599e0fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
