<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Penanganan</name>
   <tag></tag>
   <elementGuidId>a5e4f044-9c99-4477-86a8-e1d849126c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='e90Yce-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Yce-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ecd528f-c9d9-4e92-a647-db41a0c86a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e90Yce-cnt</value>
      <webElementGuid>1b971ffa-06af-41e5-a6c6-c53aaaa44dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>fe61bf6e-f0b8-4b65-8bf9-1bc59e549711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penanganan</value>
      <webElementGuid>7b7d7d0e-c33e-47c6-a621-8b3a3f1cc63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Yce-cnt&quot;)</value>
      <webElementGuid>a0fdc5a8-7864-4d99-a347-065ec2708c40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e90Yce-cnt']</value>
      <webElementGuid>1a829151-4800-4d2b-8bd1-2ba72c00e57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e90Yce-cave']/span</value>
      <webElementGuid>ca627f42-a783-4add-a482-f69eb2224141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerimaan'])[2]/following::span[1]</value>
      <webElementGuid>9c8683bd-f966-477c-862b-96849177edb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Pengaduan'])[1]/following::span[2]</value>
      <webElementGuid>ab294348-033e-418f-9b72-0a147a1f81fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen pengaduan untuk tiket saat ini'])[1]/preceding::span[1]</value>
      <webElementGuid>33c39632-7860-4fe1-8087-a8683724e4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP Konsumen*'])[1]/preceding::span[3]</value>
      <webElementGuid>c2856466-f9ec-4630-8fd9-1506d9371f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/div/span</value>
      <webElementGuid>0178c175-e955-45ee-ac1c-0b237ea041b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e90Yce-cnt' and (text() = 'Penanganan' or . = 'Penanganan')]</value>
      <webElementGuid>1f4de325-f496-4b36-9662-fa633436dca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
