<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Belum ada sub category yang dipilih_uERSl9-placeholder</name>
   <tag></tag>
   <elementGuidId>edbf58a9-2a35-4363-a24e-0be376d37368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'z-searchbox-placeholder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uERSl9-placeholder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uERSl9-placeholder' and @class = 'z-searchbox-placeholder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c1f6678-907d-454a-b165-85d9939f9e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uERSl9-placeholder</value>
      <webElementGuid>e56dfe53-eca6-4fb5-add9-8aa206201c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-placeholder</value>
      <webElementGuid>36970c93-d24e-4617-a461-46b496797101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uERSl9-placeholder&quot;)</value>
      <webElementGuid>a7760df1-ee34-44f8-8e00-10fca28f1f91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uERSl9-placeholder']</value>
      <webElementGuid>552bcb30-e9d7-40a5-814a-4df937114344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uERSl9']/div[2]</value>
      <webElementGuid>33e3ee48-a52f-45a9-b405-1258402c7742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>dc0c8179-8197-4427-a12e-86d9e94c20f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uERSl9-placeholder']</value>
      <webElementGuid>3b934ff6-a6eb-400a-8fa4-eae0a5050302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
