<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Status BAP_rXoM_9</name>
   <tag></tag>
   <elementGuidId>098f07a1-fe88-4f8a-8cda-90cc89b04428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class = 'link-view z-a']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'link-view z-a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rXoM_9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae524bc5-3102-4545-9690-a32a65ab902c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rXoM_9</value>
      <webElementGuid>5f0083fb-e31d-47bd-92a2-92a25f8dcf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-view z-a</value>
      <webElementGuid>89401d1f-21c8-4fd0-84e0-21fa56515829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/penerimaan/view/202406040506</value>
      <webElementGuid>5332c2fc-b46f-485c-9524-55914a3bf73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rXoM_9&quot;)</value>
      <webElementGuid>eee00682-e6d0-4b3c-a3a1-355a728a46ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rXoM_9']</value>
      <webElementGuid>ad90ddb8-b9d8-40b0-b182-38826cd4e0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rXoMz8-cave']/a</value>
      <webElementGuid>aa642306-3023-479c-9a84-d31343bbd85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/penerimaan/view/202406040506')]</value>
      <webElementGuid>1e4a785e-e760-4010-8e2f-d6ae954d1615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>3a727c97-282b-48f8-9ed3-e806c62cbe8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rXoM_9' and @href = '/app/penerimaan/view/202406040506']</value>
      <webElementGuid>402fbb79-44c7-4571-8708-20a1f763516e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
