<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Status BAP_rXoM_9</name>
   <tag></tag>
   <elementGuidId>098f07a1-fe88-4f8a-8cda-90cc89b04428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'link-view z-a' and @href = '/app/penerimaan/view/202406040506']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class = 'link-view z-a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rXoM_9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>793fabb2-c502-4d48-bc7e-d553b25d51b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rXoM_9</value>
      <webElementGuid>72b6bdee-2570-4cd0-a183-c7032a813ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-view z-a</value>
      <webElementGuid>e7fe2292-f098-41e1-94d0-04d766914e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/penerimaan/view/202406040506</value>
      <webElementGuid>c388ea55-909e-4e7c-91cb-8b102db9351d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rXoM_9&quot;)</value>
      <webElementGuid>5569920a-369e-4320-bd87-20ab9237e689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rXoM_9']</value>
      <webElementGuid>dedc2a5f-ea66-472a-8108-4f993dc8568c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rXoMz8-cave']/a</value>
      <webElementGuid>a7e03d34-c8c6-4987-9b31-d2c785ba8d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/penerimaan/view/202406040506')]</value>
      <webElementGuid>b780984a-5f6f-4375-8a7c-0871d0996f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>646884a2-360c-4bdc-8017-11d10728d0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rXoM_9' and @href = '/app/penerimaan/view/202406040506']</value>
      <webElementGuid>c078b118-34b8-4232-84d4-5e3fe19cb5af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
