<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>11cc1069-3874-4447-aade-075294750d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and @class = 'btn-primary full-width z-button'and text() = 'Simpan']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'g1oTj30' and @class = 'btn-primary full-width z-button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oTj30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8c0e051-4ee2-4158-88c6-75b8931be754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3475a5e-5745-4549-b5dd-0d1007eff8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oTj30</value>
      <webElementGuid>c08ca53f-d6fd-43db-b3b8-f4f009c53892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary full-width z-button</value>
      <webElementGuid>831dd4a7-54c1-4086-a04c-25c200236a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>4b150d2e-6297-4b7a-98e7-5e4f1b810542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oT7&quot;)/div[@id=&quot;g1oTn20&quot;]/div[@id=&quot;g1oTf30&quot;]/div[@id=&quot;g1oTi30&quot;]/button[@id=&quot;g1oTj30&quot;]</value>
      <webElementGuid>76121238-5be6-4f00-ad0f-f1cf0cbffaf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g1oTj30']</value>
      <webElementGuid>fe155649-5ed3-4b87-aedf-bd839532cf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g1oTi30']/button</value>
      <webElementGuid>0f058480-7bc7-4a0a-93c1-3ebae9cd3e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>ca9fbf6d-809d-4341-9874-cb390e11684c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Cabang'])[1]/following::button[2]</value>
      <webElementGuid>6c551c46-2ae9-4750-ad62-3f6af545a23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter &amp; Sort'])[1]/preceding::button[1]</value>
      <webElementGuid>b230ceac-9a3c-4407-8535-832d9b0acc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penanganan'])[1]/preceding::button[1]</value>
      <webElementGuid>178b45cf-8676-4907-ac22-e8eb6e1c67ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>2f174027-0ebb-4b10-bdf9-65006fef3d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>5ba7f7df-4e64-4498-a2c6-2d41951fabc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g1oTj30' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>472001d9-c973-4157-85b2-0727267fdb98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
