<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah_1</name>
   <tag></tag>
   <elementGuidId>9e1dc123-1662-4c58-82e5-7c5850080342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='e90Y_n']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Y_n</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8ff6f2b-2ea6-40d7-b40c-94344875ed44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2027f09d-d4e9-431d-8b0d-3543f5bb03c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e90Y_n</value>
      <webElementGuid>f6b65610-386c-4959-b50f-e8c8bf9c5aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-4 btn-upload z-button</value>
      <webElementGuid>d1aba810-00b4-4a73-9ff4-a192532a74dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>0c2ea2e0-a1ee-4bca-b56a-3af82be99c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Y_n&quot;)</value>
      <webElementGuid>ae91c8dd-d8ed-4a02-9f2e-9e640beb3b7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='e90Y_n']</value>
      <webElementGuid>d77a8346-bcf3-49cf-9cf5-cd4f7fdb23a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e90Yzm']/button</value>
      <webElementGuid>447ed76e-d8b7-4739-ba55-7e7b190ba842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[5]/following::button[2]</value>
      <webElementGuid>b084630f-2214-40d8-8e5e-c007506586e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Koordinasi PIC Penanganan ke Konsumen*'])[1]/following::button[2]</value>
      <webElementGuid>e5a81e70-1265-4228-9936-e6b881a92731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan upload dan cek tipe dokumen terlebih dahulu'])[1]/preceding::button[1]</value>
      <webElementGuid>e4928f01-47c8-4584-9922-69c1070a7389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Revisi Terkirim'])[5]/preceding::button[1]</value>
      <webElementGuid>5d0c4c16-0df6-489e-bf4a-9b883d1143eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div[3]/div/div/button</value>
      <webElementGuid>b65b3c35-78a6-4fcb-ac62-9658408d5fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'e90Y_n' and (text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>66526c1f-0005-4925-bb1a-c8856b9c1fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
