<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim</name>
   <tag></tag>
   <elementGuidId>4d52487c-90d7-4c37-ab4c-e9b414093445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='g1oTj20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oTj20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55d3b36b-b2a8-4140-8d41-392958f78710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc6a145e-7004-4744-84b6-3eef67c74678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oTj20</value>
      <webElementGuid>1b9a693b-eb68-4e73-aba4-0f408a070ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary full-width z-button</value>
      <webElementGuid>e5719e79-120b-420b-bb90-08a7591b200b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>d54d1316-ae3d-4a70-a883-96d5ddcca2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oTj20&quot;)</value>
      <webElementGuid>b0c891a9-b549-4c5b-a3e5-c50e5b109014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g1oTj20']</value>
      <webElementGuid>bd8edfab-78ce-4923-a836-70d09e17e25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g1oTi20']/button</value>
      <webElementGuid>6384123d-409f-4a1a-838d-de786d010202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kosongkan Isi Formulir'])[1]/following::button[1]</value>
      <webElementGuid>7581d518-d1b6-4a83-8270-a293c2fc1fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[1]/following::button[2]</value>
      <webElementGuid>620e1b03-0859-42da-8407-7941def8082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin ingin menyimpan data tindak lanjut sebagai berikut?'])[1]/preceding::button[1]</value>
      <webElementGuid>97cb62f0-8792-41c0-9baf-ddb843110cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Kontak'])[1]/preceding::button[1]</value>
      <webElementGuid>27e67798-17c5-451f-8304-f17d60b21b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim']/parent::*</value>
      <webElementGuid>c66b4c30-6fe6-4d62-a22b-f5990912f3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>952435ef-d2ab-49a7-b9ef-96a7e2d38eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g1oTj20' and (text() = 'Kirim' or . = 'Kirim')]</value>
      <webElementGuid>21425f22-6985-4ea5-b1d6-39ad7682bd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
