<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah</name>
   <tag></tag>
   <elementGuidId>18a96be1-3464-4e49-abcf-46dfdd2e0583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='g1oT020']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oT020</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a3a2429-921c-4864-832a-fb76ff7e13d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3697cf40-7673-4eff-9f61-549caf8c2d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oT020</value>
      <webElementGuid>1741b183-2dc2-40e3-b24b-8f2ec31c5295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary col-md-6 btn-upload button-followup full-width mb-2 z-button</value>
      <webElementGuid>632f5387-84c0-494c-926e-a8e276e5b09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>d0a2018c-68ee-4e06-a72c-96e5b144665e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oT020&quot;)</value>
      <webElementGuid>5cf0c9a1-baec-4fb0-bd8b-bb65e0b94ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g1oT020']</value>
      <webElementGuid>934be6c3-b46a-45c1-8d5d-1c299cd6e8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g1oTq10']/button</value>
      <webElementGuid>ad7ed038-d036-4089-8ef7-eecef738c763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/following::button[2]</value>
      <webElementGuid>81c1880e-4199-4d30-9288-33219ae1bfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Bukti Pertemuan*'])[1]/following::button[2]</value>
      <webElementGuid>60e88fa8-58fd-4054-86c0-baf3f29a29c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kosongkan Isi Formulir'])[1]/preceding::button[1]</value>
      <webElementGuid>17368a37-9951-4741-beda-7508d3c5737d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::button[2]</value>
      <webElementGuid>346ac9d5-b67c-4a1b-ad1b-dc08f9dd402b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah']/parent::*</value>
      <webElementGuid>23ca773e-4d68-4672-a8bd-00ed6fd261a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/button</value>
      <webElementGuid>3ce55740-946c-4ff3-87f5-1dbb5e45d478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g1oT020' and (text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>e6470f3b-7517-4c57-b3a3-e43145e36174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
