<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan_1_2</name>
   <tag></tag>
   <elementGuidId>6e236f07-2fcd-4d00-9dab-021e74d4f619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='c2YBoc0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'c2YBoc0' and (text() = '
                        Simpan
                      ' or . = '
                        Simpan
                      ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YBoc0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b541535-9d5b-4c77-a8ce-1e9a2511007e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5e629c6-6aa0-47f7-890b-901cd5d2d880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YBoc0</value>
      <webElementGuid>50466bc2-c2a6-4ea8-9a92-56e4d16e1ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-auto btn btn-primary pull-right z-button</value>
      <webElementGuid>c4705ec5-d99d-461a-a263-f7f9f0384747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Simpan
                      </value>
      <webElementGuid>e7a82d99-201f-4949-848e-bde314c01bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YBoc0&quot;)</value>
      <webElementGuid>ff1eb97e-51c2-4f25-a702-c0dbc00c4062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='c2YBoc0']</value>
      <webElementGuid>fbf60434-743c-497c-a2e1-98f92be3cc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c2YBnc0']/button</value>
      <webElementGuid>e1d6751f-c378-46f1-8c64-7270ca4534b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pembaruan Terakhir'])[1]/following::button[1]</value>
      <webElementGuid>2691cf92-9bef-430c-b5a5-3d10285b38f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::button[1]</value>
      <webElementGuid>3f9d9bca-816c-493c-9c93-d5b1add75008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::button[1]</value>
      <webElementGuid>db52cec0-af1b-4285-b771-21cafbc3d35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin ingin mengirim BAP ke pelapor dengan data sebagai berikut ?'])[1]/preceding::button[2]</value>
      <webElementGuid>0bab5102-e45d-4651-ae93-d21da686f77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>a060e74d-0fa6-4b4b-92c6-8e150ab0e13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'c2YBoc0' and (text() = '
                        Simpan
                      ' or . = '
                        Simpan
                      ')]</value>
      <webElementGuid>12f19a62-8139-4ecd-996b-40b15b2c5433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
