<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Pilih Status Detail Kontak_eT0Di00-icon</name>
   <tag></tag>
   <elementGuidId>cb0747a4-f042-4b24-81e4-8750d9606167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eT0Di00-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='eT0Di00-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>40bd1638-f31a-4d57-a9d2-fbc7acdefe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eT0Di00-icon</value>
      <webElementGuid>88270837-5711-4e96-aa3d-4a2955542015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-icon z-icon-caret-down</value>
      <webElementGuid>0b2b9b65-dc20-4e3e-8e55-4990c307b640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eT0Di00-icon&quot;)</value>
      <webElementGuid>eb75c772-88ad-4d59-af57-275c9fe35509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='eT0Di00-icon']</value>
      <webElementGuid>4aa5fdb8-e5c7-46ae-b86c-ef020418e768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eT0Di00']/i[2]</value>
      <webElementGuid>dceaba0c-505c-4f06-853e-5072678c563f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/i[2]</value>
      <webElementGuid>768ddfd6-13f3-4ebd-ac12-de9d6e96d6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'eT0Di00-icon']</value>
      <webElementGuid>181edac2-0595-4ac4-a452-6bc6b133dd3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
