<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lokasi Pertemuan_meet_location_type</name>
   <tag></tag>
   <elementGuidId>d4ddf514-f0e5-4027-96f3-8132cd5c10ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @value = 'Kantor Cabang' ]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'mSCF410-real' and @name = 'meet_location_type' and @value = 'Kantor Cabang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mSCF410-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7175553a-ed91-4949-95c3-0825d15ada08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a93f5170-c1ab-4551-9176-d6fbd00d1d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mSCF410-real</value>
      <webElementGuid>a2492ae8-58ef-4a49-8124-a1736366e28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meet_location_type</value>
      <webElementGuid>0956f0f9-dcfe-45ba-bd93-2dae006a163e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kantor Cabang</value>
      <webElementGuid>b7e33d98-cf8c-4037-a0dd-213649b95774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mSCF410-real&quot;)</value>
      <webElementGuid>aca4df21-815a-4373-b1d1-58498cd1ead3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mSCF410-real']</value>
      <webElementGuid>e4563e8a-ec89-4031-b3db-c2bc7b6c1e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='mSCF410']/input</value>
      <webElementGuid>9dba9dde-12d4-4506-9285-f297344c4cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span/input</value>
      <webElementGuid>c929d09f-c1ac-4778-a679-2f9a1cd07d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mSCF410-real' and @name = 'meet_location_type']</value>
      <webElementGuid>81138e53-0c49-420c-9d5b-a86a80feb1e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
