<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status BAP_xZWSe3</name>
   <tag></tag>
   <elementGuidId>715de889-4ba0-45f5-8d78-3f4bcc5a9bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'xZWSe3' and @type = 'text' and @placeholder = 'Cari']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'text' and @placeholder = 'Cari'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xZWSe3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3d24f3b-760e-4961-9614-6d7084d7cfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xZWSe3</value>
      <webElementGuid>852226fe-de81-4f08-9a54-90c7f84cb9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterTextbox only-numeric z-textbox z-textbox-hover</value>
      <webElementGuid>d5626102-3dbf-4fd8-b8df-7ff90929b212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cd175a2-19f3-4ca0-b13a-7934b2ab20d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>69cce6ae-23b1-4cba-b5c2-bb214ed9a913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>b6676e09-c8c0-49bb-8945-8887cdb583ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xZWSe3&quot;)</value>
      <webElementGuid>ea9f90d5-57c3-44a6-8a9c-3ca8a343181d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xZWSe3']</value>
      <webElementGuid>7a9a850c-7ff0-4323-9d31-50565012806b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xZWSd3-cave']/input</value>
      <webElementGuid>682fd001-e3a2-46dc-bc9d-2a848a949828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/div/input</value>
      <webElementGuid>1a16eb54-dbe3-454c-810b-1bb296b99c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xZWSe3' and @type = 'text' and @placeholder = 'Cari']</value>
      <webElementGuid>fbcd5345-78be-4e5c-9979-f952a9db7185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
