<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Informasi Peserta Pertemuan dari Peru_99b865</name>
   <tag></tag>
   <elementGuidId>4b88156f-53d0-49a0-adbf-ff6d81811338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c2YB_a0-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YB_a0-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eab726ee-2def-4a5b-bb30-7bcd00ec3f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>91883dd5-9667-4d34-993b-b23efa18adfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YB_a0-real</value>
      <webElementGuid>7a7b50f7-49ea-4c6e-825d-ad5c27c9ce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pght89am</value>
      <webElementGuid>a00fa70c-9279-41e8-b200-9c7d5409901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YB_a0-real&quot;)</value>
      <webElementGuid>081cb5d6-d701-476c-87d8-dbffe8a74309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c2YB_a0-real']</value>
      <webElementGuid>c9c027c1-a973-4247-9f54-efcbed08f713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='c2YB_a0']/input</value>
      <webElementGuid>9b617888-980d-47c2-8ef0-41b4e634da67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/span/span/input</value>
      <webElementGuid>bc2eae2d-4a75-41c7-93d5-360ee9ee97ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'c2YB_a0-real' and @name = '_pght89am']</value>
      <webElementGuid>2f9fe028-7a0a-467a-95a9-69f24e8cff0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
