<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waktu Pertemuan_g1oTk00-real</name>
   <tag></tag>
   <elementGuidId>1c22a8da-4f39-4122-a695-b5e94be81280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g1oTk00-real</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Pilih Waktu Pertemuan dengan Pelapor']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'g1oTk00-real' and @type = 'text' and @placeholder = 'Pilih Waktu Pertemuan dengan Pelapor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74d0cf43-545e-477d-ac81-6e79aa37b836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oTk00-real</value>
      <webElementGuid>e1044192-3234-4f50-848f-fcbcedb6cca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-datebox-input z-datebox-hover</value>
      <webElementGuid>99102216-7fc7-4e54-8eb8-b305739bd512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e3c2a83-480d-4016-b21e-31974eec260a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2a9e14ac-bb65-4a9a-b163-20a857fc5084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>g1oTk00-pp</value>
      <webElementGuid>0e5bec78-062b-478c-bc83-1f27d5fe38db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ccceaf7-10a3-46ae-ac3a-b545b88ce42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>cb6e441e-17a2-4fdd-a11a-290f079a00ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>54c035a4-0bbf-43cd-a968-59844662eaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Waktu Pertemuan dengan Pelapor</value>
      <webElementGuid>f2bfb9f2-82b5-46c6-8865-4d180f90e8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oTk00-real&quot;)</value>
      <webElementGuid>8f024186-4584-4122-ba3f-0cd8b524df27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g1oTk00-real']</value>
      <webElementGuid>b2fd318e-23dd-4fee-b3e3-8aea49232fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g1oTk00']/input</value>
      <webElementGuid>3d4d64ab-3d85-4c88-af17-f71db97a746c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>cdbb6bef-7f17-4328-94c3-7bd04fd4c1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'g1oTk00-real' and @type = 'text' and @placeholder = 'Pilih Waktu Pertemuan dengan Pelapor']</value>
      <webElementGuid>a1988f11-ffe8-4800-b49b-cc71be80d7a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
