<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Media Pertemuan__pgdnht601</name>
   <tag></tag>
   <elementGuidId>b05d70b2-d750-4928-b712-1b7a9f1c2fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' ]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'g1oTtn0-real' and @name = '_pgdnht601']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oTtn0-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>625d59cf-d211-4d2e-af56-8ed88d53e8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dddb528b-fd94-4d99-a527-a35c8f8424ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oTtn0-real</value>
      <webElementGuid>e35a2992-bc0f-4167-ae3a-2180bbc36549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pgdnht601</value>
      <webElementGuid>b39d4a3e-5697-4ed0-973f-8c0987f963d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Offline</value>
      <webElementGuid>b62d9e5c-d53f-428e-b7b6-3201a5056a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oTtn0-real&quot;)</value>
      <webElementGuid>454464f5-2981-4a31-9152-7aafa587d70e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g1oTtn0-real']</value>
      <webElementGuid>6f38599d-200e-4347-98ba-e965bf5fb65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g1oTtn0']/input</value>
      <webElementGuid>ce1483d3-c81f-4409-8043-d378c8e9cc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>9dfa82b0-17f1-425c-b015-e20b39618665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'g1oTtn0-real' and @name = '_pgdnht601']</value>
      <webElementGuid>ee918fc2-81c4-458f-9767-0f0774fcb054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
