<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Media Pertemuan__pgdnht601</name>
   <tag></tag>
   <elementGuidId>b05d70b2-d750-4928-b712-1b7a9f1c2fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'radio' and @value = 'Offline']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'g1oTtn0-real' and @name = '_pgdnht601' and @value = 'Offline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oTtn0-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf7cf05f-2d62-4070-81d2-43ce887504c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fe012fef-dbdc-4ba4-a6db-c2c862e8ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oTtn0-real</value>
      <webElementGuid>6e9afd41-e862-4d85-9dd9-fd836100a7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pgdnht601</value>
      <webElementGuid>bd06d921-d248-49d0-8408-09eb5ddbf2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Offline</value>
      <webElementGuid>787204ec-acb6-4d96-af62-a01b3f05d56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oTtn0-real&quot;)</value>
      <webElementGuid>d7fae90f-e229-4ecb-ba53-988a28879fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g1oTtn0-real']</value>
      <webElementGuid>395c3593-f777-4f19-a666-0942b6b0bab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g1oTtn0']/input</value>
      <webElementGuid>8f28a7e7-4dae-4671-a384-8cddcb4ed628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>2fdd31a1-f8d5-48cb-aa89-de33df278103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'g1oTtn0-real' and @name = '_pgdnht601']</value>
      <webElementGuid>5e0d500a-ee5b-453e-a874-395dcd7b38e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
