<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Perwakilan perusahaan dipilih untuk m_33d0ac</name>
   <tag></tag>
   <elementGuidId>a3b52226-f04f-4839-a791-694488e49a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='c2YBea0-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YBea0-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d49493e5-fad9-4658-9a56-481a7ea015ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>c2YBea0-real</value>
      <webElementGuid>33ba7627-1ace-499c-a893-b44f39582308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YBea0-cnt</value>
      <webElementGuid>5e0301aa-a666-4ad8-bd81-2e29fd533411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>ca28dd43-96a0-4312-a2da-0da58a1e0f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perwakilan perusahaan dipilih untuk menandatangani BAP</value>
      <webElementGuid>e8845026-0ad3-4933-8540-53cd4f05552a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YBea0-cnt&quot;)</value>
      <webElementGuid>31ca2b24-d8f0-4b74-bce3-d64651a63711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='c2YBea0-cnt']</value>
      <webElementGuid>a65dc1bd-a5c0-4982-ab20-dae37f743eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='c2YBea0']/label</value>
      <webElementGuid>71e539d5-68aa-4a2b-a088-f57ccaee84de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Jabatan'])[1]/following::label[1]</value>
      <webElementGuid>6e177ae9-ee6c-4139-8d91-acf1269f82e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Petugas'])[1]/following::label[1]</value>
      <webElementGuid>71bdaad4-c312-4f55-aa67-39b19eee6807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Informasi Petugas Lainnya'])[1]/preceding::label[1]</value>
      <webElementGuid>a9441e48-b670-4d94-a71a-92d7f87e8c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Peserta Pertemuan dari Pihak Pelapor / Konsumen'])[1]/preceding::label[1]</value>
      <webElementGuid>1643c4c5-ebd6-4b79-8cc8-991fb9129f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perwakilan perusahaan dipilih untuk menandatangani BAP']/parent::*</value>
      <webElementGuid>103b7b0d-79ab-46f4-af9b-d0d98edf41cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/label</value>
      <webElementGuid>7d45eee9-d859-4ec5-94a0-b0fbcfdf6d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'c2YBea0-cnt' and (text() = 'Perwakilan perusahaan dipilih untuk menandatangani BAP' or . = 'Perwakilan perusahaan dipilih untuk menandatangani BAP')]</value>
      <webElementGuid>04157bdf-1d48-4150-9c85-93008dfe540b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
