<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kantor Cabang</name>
   <tag></tag>
   <elementGuidId>13f31f8b-397b-4ba4-ab2d-e05340be1463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='g1oT410-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oT410-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>653ccce3-2426-4072-8314-59acbe823df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>g1oT410-real</value>
      <webElementGuid>1baf1885-0705-419e-b065-e53541d587ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oT410-cnt</value>
      <webElementGuid>92e6ab60-603d-45c0-a874-5f9cba50cb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>4459c623-4bcb-40ef-a1ee-e21fc8815326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kantor Cabang</value>
      <webElementGuid>dd82699d-7a70-4698-b010-b5d665366b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oT410-cnt&quot;)</value>
      <webElementGuid>a59c4b39-11e2-47d6-b448-9e1c751c753a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='g1oT410-cnt']</value>
      <webElementGuid>87e8c6ab-a5e5-4f48-8d83-1ea195d4bdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g1oT410']/label</value>
      <webElementGuid>fa8a7533-d8f3-4002-9601-5b11aa383dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Pertemuan*'])[1]/following::label[1]</value>
      <webElementGuid>f9f242b6-db00-4143-a415-21e760aad9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::label[1]</value>
      <webElementGuid>97b19ff7-0e2d-4556-907e-8ea702ac04a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rumah Konsumen'])[1]/preceding::label[1]</value>
      <webElementGuid>81253a44-0778-4564-b968-001d9ed401fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[1]/preceding::label[2]</value>
      <webElementGuid>ec540f15-2bf7-4712-be68-30cf2a92b2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kantor Cabang']/parent::*</value>
      <webElementGuid>c5fd92d0-f40b-4054-8f23-39007de42a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span/label</value>
      <webElementGuid>1e10ee4c-fddd-41d4-9991-ea62a1353203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'g1oT410-cnt' and (text() = 'Kantor Cabang' or . = 'Kantor Cabang')]</value>
      <webElementGuid>76a24230-5b7e-4c47-87f4-a26d032d65fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
