<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kantor Cabang</name>
   <tag></tag>
   <elementGuidId>13f31f8b-397b-4ba4-ab2d-e05340be1463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@class = 'z-radio-content and text() = 'Kantor Cabang']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'g1oT410-cnt' and @class = 'z-radio-content' and (text() = 'Kantor Cabang' or . = 'Kantor Cabang')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1oT410-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d835c172-6630-4de4-8a91-f3712fd204fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>g1oT410-real</value>
      <webElementGuid>b4fee501-01ec-4929-8935-5a974d84fa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1oT410-cnt</value>
      <webElementGuid>a3783a80-5330-4570-9b18-53bdcfbddb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>dbf5a437-30a9-4369-a7ee-beb3214609e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kantor Cabang</value>
      <webElementGuid>0ebbe0d9-b4e5-4c09-a7da-7824fa819820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1oT410-cnt&quot;)</value>
      <webElementGuid>211b03b0-975b-47d2-9f84-bacc0ddb295a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='g1oT410-cnt']</value>
      <webElementGuid>0e4a0809-6244-44cd-b7d5-27adec009f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g1oT410']/label</value>
      <webElementGuid>80eb6643-8024-4afc-90ad-59997de617ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Pertemuan*'])[1]/following::label[1]</value>
      <webElementGuid>003c08e4-b6b5-45ef-8f04-07d5c99978fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::label[1]</value>
      <webElementGuid>2d944ac2-0803-488c-bc73-ac652a34d949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rumah Konsumen'])[1]/preceding::label[1]</value>
      <webElementGuid>d9b12eff-6df6-4cf1-91cb-87c80cda8cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[1]/preceding::label[2]</value>
      <webElementGuid>18b78709-8e34-4331-a0f8-3d6783c31572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kantor Cabang']/parent::*</value>
      <webElementGuid>bb53190f-b115-472b-9e4a-ad6802d0b166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span/label</value>
      <webElementGuid>fa6c25ca-368c-4238-8add-3532268ddb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'g1oT410-cnt' and (text() = 'Kantor Cabang' or . = 'Kantor Cabang')]</value>
      <webElementGuid>3863823e-5e28-4569-87c5-112026fdc2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
