<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pelapor Hadir</name>
   <tag></tag>
   <elementGuidId>45085468-d432-4a97-a1a4-87a6bec32274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='c2YBxa0-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YBxa0-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5dbca38d-558e-4ac5-bf04-78f9afd15e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>c2YBxa0-real</value>
      <webElementGuid>3247a3ca-f672-467d-8c84-6185a660932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YBxa0-cnt</value>
      <webElementGuid>7dc65f04-902e-4b99-b23a-da239e7455cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>c81fbf89-23e6-4f9b-baf8-26274aae25b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelapor Hadir</value>
      <webElementGuid>1bcc1a12-0222-4bd7-a563-9208cefc1df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YBxa0-cnt&quot;)</value>
      <webElementGuid>90630dd0-74db-404b-9105-f44efa6a6b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='c2YBxa0-cnt']</value>
      <webElementGuid>85352094-1c82-4bfd-b174-80f5ddc2dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='c2YBxa0']/label</value>
      <webElementGuid>f9bf035b-4466-43de-865d-89c2769bfa84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Peserta Pertemuan dari Pihak Pelapor / Konsumen'])[1]/following::label[1]</value>
      <webElementGuid>a9eeeb9b-a6ba-494b-a531-f35b3be4502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Informasi Petugas Lainnya'])[1]/following::label[1]</value>
      <webElementGuid>ba548530-4421-4c65-87a8-404f38a65d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelapor Tidak Hadir'])[1]/preceding::label[1]</value>
      <webElementGuid>761c0ac1-5bee-4dcb-93cc-f1ef0ff17c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[2]/preceding::label[2]</value>
      <webElementGuid>3f2a76bb-a58e-4068-a5b7-3156f386b180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pelapor Hadir']/parent::*</value>
      <webElementGuid>ea527289-22f6-4132-88f2-a280f11c0723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/span/span/label</value>
      <webElementGuid>475f41fb-839f-4e96-9902-5a310d072a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'c2YBxa0-cnt' and (text() = 'Pelapor Hadir' or . = 'Pelapor Hadir')]</value>
      <webElementGuid>77fe381f-fa7f-40c6-8aae-0d88c6c90373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
