<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sepakat</name>
   <tag></tag>
   <elementGuidId>79780747-5ed2-4859-9401-6aba02ae43f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='c2YBe11-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YBe11-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5827f3fb-acb6-4b95-9998-78dca1173234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>c2YBe11-real</value>
      <webElementGuid>2b9a5c31-86ec-4484-8a97-b132b2eff86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YBe11-cnt</value>
      <webElementGuid>45a9adc1-a08a-4d7a-bceb-35a5ba4b65ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>67577b2c-060c-4cef-9340-2d110f401a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sepakat</value>
      <webElementGuid>338d3680-bc79-4432-8bf9-64d938da6af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YBe11-cnt&quot;)</value>
      <webElementGuid>049183ff-84df-452c-bb55-f61358664714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='c2YBe11-cnt']</value>
      <webElementGuid>e20709ef-9559-442a-827e-0267ad104a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='c2YBe11']/label</value>
      <webElementGuid>838ad6c9-4b11-4041-8631-791911239d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Pertemuan'])[1]/following::label[1]</value>
      <webElementGuid>9d227e6a-6b1f-49e4-9c71-b4acfafb29bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Hasil Pertemuan'])[1]/following::label[1]</value>
      <webElementGuid>780d27cb-9d4b-4f0b-8153-05d873fcebc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Sepakat'])[1]/preceding::label[1]</value>
      <webElementGuid>af52e6d3-eb45-472f-bfe3-793ddd8be242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak sepakat'])[1]/preceding::label[2]</value>
      <webElementGuid>c2a38363-c512-4818-92b9-4029a24722c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sepakat']/parent::*</value>
      <webElementGuid>7074a38c-862a-455e-852e-0b13eb586ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/label</value>
      <webElementGuid>29b74294-2716-47b6-95fe-0a355a773f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'c2YBe11-cnt' and (text() = 'Sepakat' or . = 'Sepakat')]</value>
      <webElementGuid>5ed65c54-75c0-481b-949d-9c3759b202fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
