<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dokumen</name>
   <tag></tag>
   <elementGuidId>9e604ca9-c874-4533-98e2-ddb4aa5769c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class = 'z-tab-text' and text() = 'Dokumen']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'fE5Kg1-cave' and @class = 'z-tab-text' and (text() = 'Dokumen' or . = 'Dokumen')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Yg1-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f60d4dce-18b9-4f5f-a155-9450c66a3843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fE5Kg1-cave</value>
      <webElementGuid>73b8d6a2-b988-4c69-b106-2a01b5caed80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>db2ef757-05c4-432a-ab60-9be3e2b34a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen</value>
      <webElementGuid>63050524-b8c7-4060-b7d5-ca83dc45944f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Yg1-cnt&quot;)</value>
      <webElementGuid>0c59c036-c823-4d59-9cc5-fe313bd488bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e90Yg1-cnt']</value>
      <webElementGuid>61d27db8-29a2-4847-8844-b6fe34aeb993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e90Yg1-cave']/span</value>
      <webElementGuid>3ec64f85-c477-441b-bf4e-d3a06395f83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulir'])[1]/following::span[1]</value>
      <webElementGuid>609ac178-9375-4d0d-8ced-edccf9269c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::span[2]</value>
      <webElementGuid>7317363c-e1ae-4768-a300-80aefeb2c5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pengaduan'])[1]/preceding::span[1]</value>
      <webElementGuid>c4cd02b8-bcb3-45fc-9333-377190922d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindak Lanjut'])[1]/preceding::span[2]</value>
      <webElementGuid>f5a3444d-a349-4826-92ce-b12533950658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dokumen']/parent::*</value>
      <webElementGuid>f0ce8b29-c5c3-42ba-aab9-bd14e32107a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/span</value>
      <webElementGuid>d2a5caa8-ff25-4913-9add-3c3940326348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e90Yg1-cnt' and (text() = 'Dokumen' or . = 'Dokumen')]</value>
      <webElementGuid>0a748065-a681-41b6-84f7-a0d793306145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
