<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BAP</name>
   <tag></tag>
   <elementGuidId>1eebff2c-60c7-4592-a10f-6915bd1e349a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='c2YBj1-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2YBj1-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bcb5f506-8dbf-4f81-95ce-dfbd13460c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2YBj1-cnt</value>
      <webElementGuid>7247b0ce-e833-44a0-819c-bbbfdeb2353f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>f07969b8-d870-4e84-bdc4-993aa0d0d665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAP</value>
      <webElementGuid>855b19f8-f82e-404f-83c5-bfe22bd49ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2YBj1-cnt&quot;)</value>
      <webElementGuid>3ce4a32f-f469-4198-987d-b50396ba06d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='c2YBj1-cnt']</value>
      <webElementGuid>befb429f-323a-4d31-9e8a-210915950b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c2YBj1-cave']/span</value>
      <webElementGuid>6e31eb16-ccd8-460a-a4b2-4c8df13c09a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindak Lanjut'])[1]/following::span[1]</value>
      <webElementGuid>59aa867e-2ec3-4ee8-9f63-bdbc026a4c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pengaduan'])[1]/following::span[2]</value>
      <webElementGuid>daed6111-5e2f-4061-8096-84a4f15c3005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Pengaduan'])[1]/preceding::span[1]</value>
      <webElementGuid>c5853037-bfe8-4cf0-91a3-0dfcac2cd768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerimaan'])[2]/preceding::span[2]</value>
      <webElementGuid>56f16e45-bd89-409b-8455-771f65a8a2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/span</value>
      <webElementGuid>06335db2-5402-4a49-8bf6-c0d30523ebee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'c2YBj1-cnt' and (text() = 'BAP' or . = 'BAP')]</value>
      <webElementGuid>c42e4cf9-6534-472c-8fdd-5f309c0f79e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
