<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Penanganan</name>
   <tag></tag>
   <elementGuidId>a5e4f044-9c99-4477-86a8-e1d849126c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class = 'z-tab-text' and text() = 'Penanganan']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'e90Yce-cnt' and @class = 'z-tab-text' and (text() = 'Penanganan' or . = 'Penanganan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e90Yce-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65da452d-4c23-4ac6-90b1-3fbbde6ab60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e90Yce-cnt</value>
      <webElementGuid>ce045b34-017c-4c4d-8612-5d4281d3ab4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>2181e5ef-d297-4109-bd67-011c14eb62c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penanganan</value>
      <webElementGuid>89e46312-6046-48f5-a167-1378cc509115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e90Yce-cnt&quot;)</value>
      <webElementGuid>b826c066-b9cf-4844-be0f-dae3f82a9339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e90Yce-cnt']</value>
      <webElementGuid>33310087-0285-4431-ba95-28c6cc300968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e90Yce-cave']/span</value>
      <webElementGuid>909ca57b-795e-43ea-892c-1fcdb254ac2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerimaan'])[2]/following::span[1]</value>
      <webElementGuid>c9cfeaeb-6527-4837-aa70-bffaab01c4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Pengaduan'])[1]/following::span[2]</value>
      <webElementGuid>e60aab8c-64fe-4bc0-98e6-81fa52d719ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen pengaduan untuk tiket saat ini'])[1]/preceding::span[1]</value>
      <webElementGuid>f9c5dc80-56b7-4344-92a7-201e05e981a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP Konsumen*'])[1]/preceding::span[3]</value>
      <webElementGuid>35a956f0-4362-4c36-93c2-2687e3845338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/div/span</value>
      <webElementGuid>74e22045-2ff1-45e4-94fd-8edde7208d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e90Yce-cnt' and (text() = 'Penanganan' or . = 'Penanganan')]</value>
      <webElementGuid>5b78d111-39db-444b-93bc-22eb308830e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
