<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_15</name>
   <tag></tag>
   <elementGuidId>8d910ca9-de95-4ba9-8e4c-b92852563166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_z_2-w2-p4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@class = 'z-calendar-cell z-calendar-weekday z-calendar-selected']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '_z_2-w2-p4' and @class = 'z-calendar-cell z-calendar-weekday z-calendar-selected' and (text() = '15' or . = '15')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6db310d2-86b6-4a97-aa1e-546fabb283c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_z_2-w2-p4</value>
      <webElementGuid>8e521bff-8d73-4a80-9353-dec18dce8a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-calendar-cell z-calendar-weekday z-calendar-selected</value>
      <webElementGuid>31a15977-5fd2-47e7-9a4b-7b88d21cd8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>15 Agustus, 2024</value>
      <webElementGuid>443c0a9a-bf5a-473f-9792-e2fb1317da8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>8f8c1f78-1f5b-462f-b04f-a6cecbba9f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_z_2-w2-p4&quot;)</value>
      <webElementGuid>ac9dde7f-9ce7-440a-aa25-340f62876970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='_z_2-w2-p4']</value>
      <webElementGuid>b4d91e28-fb11-4897-8d16-4238860e4039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_z_2-w2']/td[5]</value>
      <webElementGuid>6a7ed4a1-9d12-4421-8167-79f95769b547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sab'])[1]/following::td[19]</value>
      <webElementGuid>ab27bebb-73dd-462e-83c1-a5aaaa77a464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jum'])[1]/following::td[19]</value>
      <webElementGuid>a957fd42-af84-4bda-9bac-5f56294280c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15']/parent::*</value>
      <webElementGuid>2cbc43bd-3588-4583-85d9-aad7aa494362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]</value>
      <webElementGuid>efc7b555-fb16-4262-9318-e7d56597fba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '_z_2-w2-p4' and (text() = '15' or . = '15')]</value>
      <webElementGuid>b12888ca-2b3e-457e-9086-69cc5b8ccc6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
