<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Belum ada sub category yang dipilih_uERSl9-placeholder</name>
   <tag></tag>
   <elementGuidId>05b707ec-f266-40f2-8915-8ce215f9f651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uERSl9-placeholder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uERSl9-placeholder' and @class = 'z-searchbox-placeholder']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'z-searchbox-placeholder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ced7409c-2b80-49c5-834e-d04ab0ef59e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uERSl9-placeholder</value>
      <webElementGuid>f71cc288-0d5f-4961-a45d-073037c22c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-placeholder</value>
      <webElementGuid>eb0bb919-2eb8-416c-8ce5-55dc16f233a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uERSl9-placeholder&quot;)</value>
      <webElementGuid>374a5474-faf1-4b92-a7b9-767ce25c45c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uERSl9-placeholder']</value>
      <webElementGuid>4af1432b-55b6-423e-8b7e-6e055f736b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uERSl9']/div[2]</value>
      <webElementGuid>922a023d-7bce-4f47-a199-008dd25d6e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>8a463e75-f49d-4fa1-95d3-179d81eee366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uERSl9-placeholder']</value>
      <webElementGuid>fa4eff78-44fa-4509-b27f-71b8d159dbe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
