<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , uERSl9-search, , ))_uERSl9-search</name>
   <tag></tag>
   <elementGuidId>029a1f09-b352-4a85-8be6-78b6f26d39eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uERSl9-search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uERSl9-search' and @type = 'text' and @placeholder = 'Type to search']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[ @type = 'text' and @placeholder = 'Type to search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>845c9234-2a36-42bd-a76e-47edda8d023d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uERSl9-search</value>
      <webElementGuid>3fbf1d43-6c43-4a68-80ba-09b19dc09beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-search</value>
      <webElementGuid>3ec71842-d280-4661-a182-10b1a15a4a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>055325bd-6364-457d-abf5-0d99b030d855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7323ceea-5709-4bf0-ba57-d90b68adad03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to search</value>
      <webElementGuid>1d6d360f-4e63-4b38-8c49-03be0c5588cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uERSl9-search&quot;)</value>
      <webElementGuid>b7b089b6-6763-4b33-8a69-365e2faccfe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uERSl9-search']</value>
      <webElementGuid>81bbee52-53cc-4f5f-a792-df0ea041a4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uERSl9-pp']/input</value>
      <webElementGuid>4f9390bd-82b1-4981-a1b0-17f1b202f0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2aecc2c5-4608-47cb-b3d5-4e7f40fc267b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uERSl9-search' and @type = 'text' and @placeholder = 'Type to search']</value>
      <webElementGuid>e5b7c956-e960-4d5c-a19e-030f4f912ed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
