<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih</name>
   <tag></tag>
   <elementGuidId>d9f241fa-d352-44fb-9784-201dfb19d560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and text() = 'Pilih']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d73L1_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43f5f468-ffe1-462a-b4ce-0c09b21956f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa825be3-bdcf-4769-a71d-755afd6e9c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d73L1_0</value>
      <webElementGuid>bb6b1c99-1a46-41e4-a6b5-30d2fff13950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary  z-button</value>
      <webElementGuid>6ebb1b7e-20c3-4f7e-8afa-d728c404ff39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>f64d31f7-d1d9-40cc-bbd1-555f690859f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d73L1_0&quot;)</value>
      <webElementGuid>bd944bca-2812-416c-8c31-0f53b7488483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='d73L1_0']</value>
      <webElementGuid>5b33a55e-df4b-4fca-bbab-04020e359116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d73L__0']/button[2]</value>
      <webElementGuid>d86c66a6-2637-403c-92f8-dc72a438544f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[1]/following::button[1]</value>
      <webElementGuid>02005db2-c7d1-4090-968c-3bfcb69b79be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AC'])[1]/following::button[2]</value>
      <webElementGuid>ae4b641f-d7d9-4885-ada1-070d55cd9231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Kontrak 951001526611'])[1]/preceding::button[2]</value>
      <webElementGuid>c3d5a10e-f327-405b-af3a-2f020aefbed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih']/parent::*</value>
      <webElementGuid>c65b6b61-cae4-4cd3-a57b-4acc031b0b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>85611b66-b94d-4817-a490-51859f114443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'd73L1_0' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>04c1a734-abbf-4710-a983-6735d2ecbc98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
