<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No.Kontrak</name>
   <tag></tag>
   <elementGuidId>7c16a483-31dd-4091-9f61-52a1ddbc3fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'No. Kontrak' or . = 'No. Kontrak')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rO3Sr1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c58bb293-2658-4e97-8ec8-92b033ec9f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rO3Sr1</value>
      <webElementGuid>bbda2b6f-8c3c-40d1-9a50-712ece72958a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem z-comboitem-selected</value>
      <webElementGuid>269e4361-d889-49d5-b174-bb0e98460e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No. Kontrak</value>
      <webElementGuid>062b9250-4c1e-400b-8876-56dc8310fb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rO3Sr1&quot;)</value>
      <webElementGuid>72ed43dd-5680-4e5f-becc-5ffb24f5906b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='rO3Sr1']</value>
      <webElementGuid>efd123e2-6e4f-412c-bd70-09ba84b4d792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rO3Sp1-cave']/li[2]</value>
      <webElementGuid>9cb70975-1bb7-4284-95df-fba06708e88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[4]/following::li[1]</value>
      <webElementGuid>ecbc5004-e5c4-4157-8799-b838f1ae6562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]</value>
      <webElementGuid>b0e6094b-7bbd-48e1-beec-8772d6e021e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'rO3Sr1' and (text() = 'No. Kontrak' or . = 'No. Kontrak')]</value>
      <webElementGuid>7618c7f3-4c35-4767-af01-d84383e89b9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
