<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>0e5caa03-38a2-4993-83d3-c6d9e0afe457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nIPPc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'password' ]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nIPPc' and @type = 'password' and @name = 'password' and @placeholder = 'Masukan Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eb382d5-2953-4430-b511-04b943b67d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nIPPc</value>
      <webElementGuid>b198c288-3dde-4209-b54a-681477caa8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox z-textbox-hover</value>
      <webElementGuid>191de060-0426-470a-99b3-ba82fafdf828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>316f191a-dc6c-4c00-9aa1-75d76e35b08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>22a17621-6a94-4c66-a487-2198845bd521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Password</value>
      <webElementGuid>191acbc6-8cd7-41a0-8f06-73fb4f6a22b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nIPPc&quot;)</value>
      <webElementGuid>7416bb6a-12c0-469b-af8c-3a643c983956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nIPPc']</value>
      <webElementGuid>b1ea984d-5da0-4136-b167-939d407a5b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nIPPb']/input</value>
      <webElementGuid>425fb44d-a156-4725-b7ad-7e9a1ba3ada3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4d58c1eb-5323-43d5-8545-6ea56e15d0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nIPPc' and @type = 'password' and @name = 'password' and @placeholder = 'Masukan Password']</value>
      <webElementGuid>627630e9-a54e-4f63-afa3-a32c8c43dda9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
