<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPK_username</name>
   <tag></tag>
   <elementGuidId>54c3dc6b-b085-491a-88da-50956d260f3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nIPP6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nIPP6' and @type = 'text' and @name = 'username' and @placeholder = 'Masukan NPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9acfeede-9cfa-4dbd-8758-9942f0ed8444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nIPP6</value>
      <webElementGuid>1ca86aaf-2555-4d31-bc69-310285057112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox z-textbox-hover</value>
      <webElementGuid>a0a900dc-e23e-482c-9e1a-25e969801684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>558a8cbc-b68d-4555-b5ed-dac6d2a1e70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f3aa17f-30f0-4ab2-bc31-b17685d73791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ff8ae36a-d558-4381-96f7-7154926d6d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan NPK</value>
      <webElementGuid>927fa546-ef9a-498f-b5d2-9b8ffb56b2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nIPP6&quot;)</value>
      <webElementGuid>647bcf17-c777-4841-a367-525d34e38830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nIPP6']</value>
      <webElementGuid>1333f269-2181-49f2-944f-ed7a8ebfa497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nIPP5']/input</value>
      <webElementGuid>9c491120-b65b-480b-9d84-1a5b73290965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>22ac5007-5b51-4c43-87d1-2efcbbd7a436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nIPP6' and @type = 'text' and @name = 'username' and @placeholder = 'Masukan NPK']</value>
      <webElementGuid>b4d1263f-c716-4e61-8914-ef7248cb6e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
