<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah (1)</name>
   <tag></tag>
   <elementGuidId>7f783c5f-8862-4d94-80a8-2120ff632d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'aDjOyi1' and (text() = 'Unggah' or . = 'Unggah')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aDjOyi1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='aDjOyi1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>192dd334-de7d-4517-8733-95f7d0547a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82f804cf-4008-48a1-975a-521dac4fc296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aDjOyi1</value>
      <webElementGuid>560be600-5f90-43e8-9f11-ef4ff76f75c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-4 btn-upload z-button</value>
      <webElementGuid>47f65030-cd6a-417b-a516-6147d92f7e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>df4a4f42-8f6a-4142-b49a-ed1f156521b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aDjOyi1&quot;)</value>
      <webElementGuid>0f3a97d3-b1ab-4b1b-b67a-afda21518b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='aDjOyi1']</value>
      <webElementGuid>a213ee3d-1c1c-4702-b79d-c519ad18b3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aDjOxi1']/button</value>
      <webElementGuid>633609dc-56c5-4ef1-b570-64b9d878349e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/following::button[2]</value>
      <webElementGuid>9d2af568-c565-48ef-93d8-a289702fde32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/following::button[2]</value>
      <webElementGuid>c5ec569a-be58-49ba-a9a4-16547359ef9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Template'])[1]/preceding::button[1]</value>
      <webElementGuid>12cd0e56-c026-4e7f-b300-387114a2e97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan upload dan cek tipe dokumen terlebih dahulu'])[1]/preceding::button[2]</value>
      <webElementGuid>47b56ef7-a3b9-4acf-9977-040ad8d5c06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah']/parent::*</value>
      <webElementGuid>e17935e6-8cb6-4c48-8e66-8fbd8e7c9859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/button</value>
      <webElementGuid>25a3fc37-2b23-4153-8e21-9407ec3190b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'aDjOyi1' and (text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>76dfa205-a025-49fa-899e-28d59942916a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
