<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah</name>
   <tag></tag>
   <elementGuidId>6c62ec00-8118-4195-8c80-a0bc379bb74e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'aDjOyi1' and (text() = 'Unggah' or . = 'Unggah')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aDjOyi1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type = 'button' and text() = 'Unggah'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c265afff-3db9-439e-abf4-40835a7e774b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27da5ad7-e2aa-4947-afd7-5c241712d40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aDjOyi1</value>
      <webElementGuid>4b8e5dc0-c3f8-476c-8a29-a991e28429a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-4 btn-upload z-button</value>
      <webElementGuid>dc2e72a4-987d-44e9-ac14-509e1f60cd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>a1499407-6227-4a7e-90db-f93e2638dd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aDjOyi1&quot;)</value>
      <webElementGuid>460a61c6-4870-410b-8282-72cd475e41aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='aDjOyi1']</value>
      <webElementGuid>7a4df625-90e9-4636-87d5-cb6824a12ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aDjOxi1']/button</value>
      <webElementGuid>56dcf132-b522-4277-815c-c8e711af3420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/following::button[2]</value>
      <webElementGuid>4b68c85c-b8d7-4942-9f16-ef437d18e9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/following::button[2]</value>
      <webElementGuid>d754cef5-9ff8-4b17-aec0-31fe3896d8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Template'])[1]/preceding::button[1]</value>
      <webElementGuid>f9570057-71b3-449f-b3a1-bc367aa6a811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan upload dan cek tipe dokumen terlebih dahulu'])[1]/preceding::button[2]</value>
      <webElementGuid>ef5ee649-2a1b-4cac-a141-254179c3351f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah']/parent::*</value>
      <webElementGuid>799ffe8b-3932-4213-8bbf-c5815355b537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/button</value>
      <webElementGuid>81bf317e-927c-42ad-955b-3e5f5c376e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'aDjOyi1' and (text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>125d3c72-e93d-46c0-8dda-1a84c6d65a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
