<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unggah</name>
   <tag></tag>
   <elementGuidId>27504852-b4c8-4a9a-a18f-85527f402a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aDjOxi1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aDjOxi1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ebe8ab6-e47e-412c-b5d9-cfdc077dc696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aDjOxi1</value>
      <webElementGuid>91a0ebe7-715d-4530-9ada-77d5abec4713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 px-0 col-xs-12 document-button z-div</value>
      <webElementGuid>b16914c4-950e-4bf3-9b5b-0a82b6806912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unggah</value>
      <webElementGuid>703fc351-dd14-47bf-a6ed-da45ca50999c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aDjOxi1&quot;)</value>
      <webElementGuid>c4c0ba61-b53d-4bad-8e91-7a3da8011e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aDjOxi1']</value>
      <webElementGuid>513f300c-03bc-498d-9054-a57520a97afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aDjOwi1']/div</value>
      <webElementGuid>6d3b470c-0068-4546-a85e-a2d682485672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/following::div[3]</value>
      <webElementGuid>deff2809-e310-4918-8887-98e7b8671514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/following::div[5]</value>
      <webElementGuid>789488b9-b7b4-4027-a020-2078288a7f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Template'])[1]/preceding::div[2]</value>
      <webElementGuid>88bba6fa-7461-4318-9812-fad60bbe969c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[3]/div/div</value>
      <webElementGuid>d8914d41-af3e-4864-bdb6-2371ccb3d48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aDjOxi1' and (text() = ' Unggah' or . = ' Unggah')]</value>
      <webElementGuid>e659482d-9c61-4136-9b7d-9d7dd4dac268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
