<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Surat Kuasa</name>
   <tag></tag>
   <elementGuidId>467d4484-37ce-41c0-b56d-05082dd12306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'p3iIos1-cnt' and (text() = 'Surat Kuasa*' or . = 'Surat Kuasa*')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p3iIos1-cnt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[text() = 'Surat Kuasa*'])[4]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4c6e4850-3c56-4fe7-aae5-74544aaf85a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>p3iIos1-real</value>
      <webElementGuid>02cdab29-e1df-44c6-a21e-6631b968d4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p3iIos1-cnt</value>
      <webElementGuid>be601df1-f522-4194-99be-a60d37fa04d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>3c5c9dea-f62d-4ce0-b87b-74635a465dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Surat Kuasa*</value>
      <webElementGuid>79a652f9-79f7-47c1-82d5-a9acc68a20d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p3iIos1-cnt&quot;)</value>
      <webElementGuid>2fdf106d-530f-4cfe-b879-50c024b53ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='p3iIos1-cnt']</value>
      <webElementGuid>7fd291b4-8e63-468f-aa8e-862c85d234d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='p3iIos1']/label</value>
      <webElementGuid>a6741720-8d32-4ce4-b49c-10bcd9e66a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan*'])[1]/following::label[2]</value>
      <webElementGuid>5a5c995e-ed5c-4929-a370-bc4091c467f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/preceding::label[1]</value>
      <webElementGuid>bcd5e14e-cd56-4b86-b5dd-996939ec2de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/preceding::label[2]</value>
      <webElementGuid>e7126b61-e6af-4267-9ab8-52076c84d9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Surat Kuasa*']/parent::*</value>
      <webElementGuid>44953bfc-f605-4654-ada3-072d1222a679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/label</value>
      <webElementGuid>c0e44139-374d-4983-ab11-917266c40cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'p3iIos1-cnt' and (text() = 'Surat Kuasa*' or . = 'Surat Kuasa*')]</value>
      <webElementGuid>b20376c4-9f43-43c6-bb16-624f0c3cac14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
