<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ambil_1</name>
   <tag></tag>
   <elementGuidId>8ed5eb96-bb46-4b03-8037-0844e65f3262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vVsPz6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button'and text() = 'Ambil']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'vVsPz6' and (text() = 'Ambil' or . = 'Ambil')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db34e389-ffe6-464d-9411-b17f03cee358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>526a7f5b-5952-44ce-a4de-02d5810357ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vVsPz6</value>
      <webElementGuid>5739eb5a-6bcd-4e74-8d60-0e258b755533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary full-width btn-do-take-assignment z-button</value>
      <webElementGuid>7e65dccb-ca3e-42b7-8198-93e417eaed1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-code</name>
      <type>Main</type>
      <value>202408040202</value>
      <webElementGuid>bbf03f59-55e7-4004-aa12-b80a4defd98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ambil</value>
      <webElementGuid>de092aa4-3bf3-4458-889d-275b1710d741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vVsP7&quot;)/div[@id=&quot;vVsPv6&quot;]/div[@id=&quot;vVsPy6&quot;]/button[@id=&quot;vVsPz6&quot;]</value>
      <webElementGuid>519f580b-ad13-4ef3-9a20-031401f68438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='vVsPz6']</value>
      <webElementGuid>be96f2d7-6564-4b9b-a626-ebff186d442a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vVsPy6']/button</value>
      <webElementGuid>df6a66f0-9a4e-40e8-a252-cebe5f07ef29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>7e19fb4f-38e4-4e24-bda7-46f0753d3adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lengkap'])[1]/following::button[2]</value>
      <webElementGuid>ceb46c92-4358-441e-a579-caa0256cd4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter &amp; Sort'])[1]/preceding::button[1]</value>
      <webElementGuid>fe4b407a-5468-40a9-874c-859bff9dd365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penanganan'])[1]/preceding::button[1]</value>
      <webElementGuid>36a487e1-11e0-4952-96da-f3babb893217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ambil']/parent::*</value>
      <webElementGuid>03d28a76-4cbd-4809-b560-6656cc6127ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>4f57e651-d95e-4e78-b691-eea1052cac9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'vVsPz6' and (text() = 'Ambil' or . = 'Ambil')]</value>
      <webElementGuid>1ea578c2-2335-4a1e-9463-49ea5e2caed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
