<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ambil</name>
   <tag></tag>
   <elementGuidId>80b1f004-5106-47d1-96bd-92d78c5df533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vVsPe5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button'and text() = 'Ambil']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'vVsPe5' and (text() = 'Ambil' or . = 'Ambil')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>134ac75a-fbae-467d-97b3-5ecb33e67064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d74aaa5f-b234-4174-82c8-9a002b95f74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vVsPe5</value>
      <webElementGuid>8bb62bf4-906b-4ffc-9dc1-c7d980f587ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary z-button</value>
      <webElementGuid>ed6f404b-2527-4026-ad2b-a5de40ccfa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ambil</value>
      <webElementGuid>c124183c-d725-497c-a8d6-ec8c42f6892a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vVsPe5&quot;)</value>
      <webElementGuid>6d1f1769-0063-4cea-bdf6-629e05337d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='vVsPe5']</value>
      <webElementGuid>6e0699bb-4938-43b3-a63d-d580d2be14b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vVsPc5']/button[2]</value>
      <webElementGuid>e37b6b66-4a7b-4f15-8f13-27139579db0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>25a938d9-0cca-4970-b433-7bc35e02ba52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengerti'])[1]/following::button[2]</value>
      <webElementGuid>a2559e17-d2bc-4597-bd82-8866a07fba8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengambil Tiket'])[1]/preceding::button[1]</value>
      <webElementGuid>fe45ba3e-bfd2-4d09-b12e-fca0f5d73201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ambil']/parent::*</value>
      <webElementGuid>24701f5e-2a22-4b35-984c-30764d96b3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e5985976-9f9b-462c-be34-c22b1fa9a76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'vVsPe5' and (text() = 'Ambil' or . = 'Ambil')]</value>
      <webElementGuid>fcbeaf85-fe5f-47d7-865f-6dca4c26f1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
