<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Kontrak_qARZk4</name>
   <tag></tag>
   <elementGuidId>2a2ad0d9-b443-4b3e-a01f-ccbfc585ee73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'text' and @placeholder = 'Cari'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qARZk4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'qARZk4' and @type = 'text' and @placeholder = 'Cari']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef37e983-54c3-43c8-bebd-2c46d0d8e6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qARZk4</value>
      <webElementGuid>14c690f7-1f40-419d-9a5d-ee4a436b842b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterTextbox only-numeric z-textbox z-textbox-hover</value>
      <webElementGuid>a22ee1e4-2c0e-470b-afcd-b66df2d8caf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6f8c467-0e80-4bf0-bfc1-18b4e5e2a7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>7dfb791c-c725-43ab-ae02-484bf477d5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>8cbae982-5b9b-48cb-8c09-9840805f58cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qARZk4&quot;)</value>
      <webElementGuid>cd1da35f-9c09-4e69-b78b-fc88a9f0635a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qARZk4']</value>
      <webElementGuid>2de28c2a-52a3-4345-9922-50170815e727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qARZj4-cave']/input</value>
      <webElementGuid>59ea0a55-b90b-41f5-b81b-57bad2badb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/input</value>
      <webElementGuid>2e92b8f6-a741-40fc-bb29-12cb09d337f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qARZk4' and @type = 'text' and @placeholder = 'Cari']</value>
      <webElementGuid>b7338c50-5146-48dc-9627-bfc7abb2f271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
