<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>2aa59b1f-b16f-4480-b941-943b9e1667c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o5YVc</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'o5YVc' and @type = 'password' and @name = 'password' and @placeholder = 'Masukan Password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6c7e029-0627-45b6-8a8a-b144a09fa611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o5YVc</value>
      <webElementGuid>3dade02a-b06e-4ba4-a03d-522365d2cda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox z-textbox-hover</value>
      <webElementGuid>21fa1d6f-4ddd-4216-97e7-e930995c7364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>adabb786-b772-415e-bf4d-17b733ac773d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>392085eb-526c-4dd0-9f94-73386577c46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Password</value>
      <webElementGuid>8f05dbd3-c3a7-4f12-bfd1-38ebb6fc8213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o5YVc&quot;)</value>
      <webElementGuid>0af6ed52-f88c-4e63-8591-29ef41de8d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o5YVc']</value>
      <webElementGuid>897ec226-fb59-4db3-851f-fb0960a46553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='o5YVb']/input</value>
      <webElementGuid>216068c3-e475-46ef-8165-82e9874032b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d78fa9e5-6ef6-4e68-9a1d-8826fa9217eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'o5YVc' and @type = 'password' and @name = 'password' and @placeholder = 'Masukan Password']</value>
      <webElementGuid>64fd5e31-7489-4b36-93f5-8fba67c284be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
