<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPK_username</name>
   <tag></tag>
   <elementGuidId>1a482bfd-0aef-433a-96f2-65fa63274bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o5YV6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'z-textbox z-textbox-hover' and @type = 'text' and @name = 'username' and @placeholder = 'Masukan NPK']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cedbcd4a-e9db-4266-940a-d742e5cc58f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o5YV6</value>
      <webElementGuid>60bd81f0-6664-426f-9dfd-e3319f82fbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox z-textbox-hover</value>
      <webElementGuid>43a9a6d0-d7f6-492e-b3a1-02a01092f6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8390027f-0146-42a5-9209-0c2a40fee844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27e1e662-da45-4fcc-885a-4db73f042c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>7b3034ab-3c35-4eab-8a8f-89f4d094ca6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan NPK</value>
      <webElementGuid>73985b84-63f7-4911-b074-f541e0996ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o5YV6&quot;)</value>
      <webElementGuid>705d7997-9d49-4d4a-97e6-f5365fd38916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o5YV6']</value>
      <webElementGuid>beacdaf4-a465-4d2a-8132-197b9cf2d0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='o5YV5']/input</value>
      <webElementGuid>2e4e510f-592a-4809-a905-a27b14500d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>df2017b8-7e66-49d4-a192-5122cab341c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'o5YV6' and @type = 'text' and @name = 'username' and @placeholder = 'Masukan NPK']</value>
      <webElementGuid>f6b116d0-7fdd-47eb-b6f5-f8df5e95eee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
