<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No.Kontrak_search_value</name>
   <tag></tag>
   <elementGuidId>98f19bb5-3a3d-40d7-833a-b177da40a8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sQjFs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sQjFs1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddc43104-2a33-4a37-979c-d1d2d7e62dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sQjFs1</value>
      <webElementGuid>42d35f82-3ae5-430b-b20a-78fc3841a9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-mt-0-3 max-length required only-numeric z-textbox z-textbox-hover</value>
      <webElementGuid>1f51db72-ddee-46c7-a4a8-623736eaee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10b70980-ca59-42ae-ba6d-d608409d6b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c1a49292-9744-4fee-8b11-10720708c3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_value</value>
      <webElementGuid>ce3ed285-bcbf-4fb7-87ec-1f4053d5c6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Kontrak</value>
      <webElementGuid>890817f0-f6fa-457b-852f-f3a42cb71453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sQjFs1&quot;)</value>
      <webElementGuid>a2c95b5d-e92f-4962-839d-ef80ecd2441c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sQjFs1']</value>
      <webElementGuid>b99e88b5-e60b-468e-8d71-e57216f2e7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sQjFo1']/input</value>
      <webElementGuid>e859512b-ebeb-48d9-a05e-602325083d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b8ffe991-b8cc-4997-8443-867fbf00644e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sQjFs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      <webElementGuid>7db7de6a-e192-48d6-8e89-943a566da17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zOgEs1']</value>
      <webElementGuid>71fee8da-66eb-4dad-802f-5d582ec907b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zOgEo1']/input</value>
      <webElementGuid>6bb9cd53-5657-423e-9d35-d65bc4de40c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zOgEs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      <webElementGuid>1d679453-865e-4324-b61f-294ec21fa209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
