<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Pengaduan Konsumen Minimal 400 Karakter tidak termasuk tanda baca_detail_complaint</name>
   <tag></tag>
   <elementGuidId>b83efc41-42f1-4e53-a784-cfd0deed39ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pQNQ4d' and @class = 'required min-length z-textbox z-textbox-hover' and @dependon = 'detail_complaint' and @name = 'detail_complaint' and @rows = '5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pQNQ4d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name, 'detail_complaint')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3e4b0651-b587-4720-bfaa-eee764319188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pQNQ4d</value>
      <webElementGuid>ae11fbe2-4610-4ef4-90eb-bb7223cd3885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required min-length z-textbox z-textbox-hover</value>
      <webElementGuid>18801731-9a53-4ec3-8da6-c6be2d4b8dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependon</name>
      <type>Main</type>
      <value>detail_complaint</value>
      <webElementGuid>be7510e5-bd78-4a03-a6ae-8e5cd1fb1dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-length</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>eec683c6-23f0-4985-978d-8e96a4a32ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detail_complaint</value>
      <webElementGuid>a1faef01-c300-4bfa-b22f-4d8e7d94bda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>72eeddd0-c5e3-4029-9055-1f68e5b25a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pQNQ4d&quot;)</value>
      <webElementGuid>835356b1-1ffb-4ad9-8903-6a381e03b614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pQNQ4d']</value>
      <webElementGuid>cf9595ea-82f7-43a1-93d3-a32464b20219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pQNQ0d']/textarea</value>
      <webElementGuid>ed23aea9-98ab-42b7-b791-26e84e072bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/textarea</value>
      <webElementGuid>1a80b5b9-df3e-4fa1-a790-f6e13acfbae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pQNQ4d' and @name = 'detail_complaint']</value>
      <webElementGuid>ef04216c-cdba-411e-8c92-9351ecccba7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
