<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPK_username</name>
   <tag></tag>
   <elementGuidId>5385ceab-0795-4acd-8120-9c1c83d3d5df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o5YV6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'z-textbox z-textbox-hover' and @type = 'text' and @name = 'username' and @placeholder = 'Masukan NPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4fb2972-96bf-43f8-a169-90b748995669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o5YV6</value>
      <webElementGuid>89da33bb-59bb-4bbb-a479-b6595f30e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox z-textbox-hover</value>
      <webElementGuid>de51b4a5-77da-412a-bcf9-d2211a0126db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d70572dc-6b51-4009-a3aa-c723af23bcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68f33e1f-f0ce-4713-830b-c13325e02a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ed8ed1c9-0b96-4ccc-8bb9-9605b6229811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan NPK</value>
      <webElementGuid>657a7a26-3420-4732-9cab-f4f741e665a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o5YV6&quot;)</value>
      <webElementGuid>1a6d0c74-3bda-430b-be79-99c239802c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o5YV6']</value>
      <webElementGuid>d9833507-03b0-4be4-a897-a9e0ac8ed237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='o5YV5']/input</value>
      <webElementGuid>d47b3c77-7097-4fba-b1d7-836cda34414b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>597b91a1-8902-4fb2-a5ee-cf091c3af3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'o5YV6' and @type = 'text' and @name = 'username' and @placeholder = 'Masukan NPK']</value>
      <webElementGuid>c52dc231-bcdf-4efc-bfd7-0e49678d76f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
