<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Handphone_update_phone_number</name>
   <tag></tag>
   <elementGuidId>c804b83c-9a0d-4f6e-b6e3-6a385e9de593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e3FPa3-real</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'e3FPa3-real' and @name = 'update_phone_number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>056b0a09-fc9b-412e-ba8c-09cc063cd409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>db2a5ec7-d545-4aea-aa32-4d238891a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPa3-real</value>
      <webElementGuid>0128161e-4d2e-4605-8e22-3ef9bf2a85cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>update_phone_number</value>
      <webElementGuid>932dc526-343a-48c0-9497-19a49e7266e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>4a5277de-978d-479b-b3d4-fa3fb4fea906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPa3-real&quot;)</value>
      <webElementGuid>b90e8a1e-e781-4ed6-8ec6-5a4da856b062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPa3-real']</value>
      <webElementGuid>497b5fd9-d624-4fc3-89fa-01c7c1f303c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='e3FPa3']/input</value>
      <webElementGuid>bd95538e-5da3-4615-8055-d0a3c9369476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span[2]/input</value>
      <webElementGuid>a80fddbf-8d94-4ec4-a80d-4bf1d2cc982c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'e3FPa3-real' and @name = 'update_phone_number']</value>
      <webElementGuid>431bc9d4-7739-4832-9964-da233a7e5476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
