<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_update_customer_email</name>
   <tag></tag>
   <elementGuidId>2e1757f4-f986-422a-bd60-f7957596e858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iNEFi3-real</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @name = 'update_customer_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fe29e18-73e6-4432-84c8-77b51c0052ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f22b3df7-be91-464d-944d-aaf1a6b13860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iNEFi3-real</value>
      <webElementGuid>7c6663e7-d2cc-4a52-850a-8151ad4f3646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>update_customer_email</value>
      <webElementGuid>69dc1f10-cf8a-428d-8e3c-f09b09aad648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>5843cb1c-f6a2-43e9-8730-67b531b241f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iNEFi3-real&quot;)</value>
      <webElementGuid>8aea2623-d6b5-4645-b09e-1f23af6a4772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iNEFi3-real']</value>
      <webElementGuid>517e28ce-b17b-4ecc-bb52-3426301befcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='iNEFi3']/input</value>
      <webElementGuid>488b96d6-4fdf-4edc-8fe9-042477a51398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]/input</value>
      <webElementGuid>4f362cec-1559-4dd8-babd-5907ae8f64a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'iNEFi3-real' and @name = 'update_customer_email']</value>
      <webElementGuid>837d95c3-d8be-4b4a-9caf-8217fe132cb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
