<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_update_phone_number_update</name>
   <tag></tag>
   <elementGuidId>4c018fb9-6213-40d9-8c70-bcf34e9af635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e3FPb3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number' and @name = 'phone_number_update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c367ca7c-5801-4a25-8869-aed9486ad6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPb3</value>
      <webElementGuid>689aab68-92f0-4492-8b73-68f398d05d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-length required z-textbox z-textbox-hover</value>
      <webElementGuid>c0e0f906-7422-49b6-9f68-3434b20f5949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>72584b70-5574-42f4-bf85-2ca9460846a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-length</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>45c0b66b-c273-4ba2-9be1-a909ff68745f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>b617eacb-5b50-445a-b8e9-a6714b53abfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number_update</value>
      <webElementGuid>dfaee095-b689-41a0-a3ac-0860a993439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPb3&quot;)</value>
      <webElementGuid>ffc92256-cb69-40dc-8e59-d917c6cc799e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPb3']</value>
      <webElementGuid>d41b0b09-7717-4c85-abe9-fbdf064a76ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3FP73']/input</value>
      <webElementGuid>68ea31d7-40d7-478f-a607-e1675141b10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>4794dd39-db92-431c-b622-375f510784a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3FPb3' and @type = 'number' and @name = 'phone_number_update']</value>
      <webElementGuid>32d3c3a1-116b-44da-996d-adcc909690ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
