<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_update_customer_email_update</name>
   <tag></tag>
   <elementGuidId>2de12845-6498-40dd-9cd1-9f568c8ac5c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e3FPj3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and @name = 'customer_email_update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5660c8cc-2780-453c-8db3-07d6c988c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPj3</value>
      <webElementGuid>46a2e6e4-08ee-4f16-8cda-7857c6a951e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required email z-textbox z-textbox-hover</value>
      <webElementGuid>aaa55711-df30-43e0-a0ea-ebee205463fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f075049a-5002-4161-9899-ce74ca37ffed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_email_update</value>
      <webElementGuid>da5ea9ed-1ab0-432c-8f9c-40e902c41b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPj3&quot;)</value>
      <webElementGuid>d6d97220-6e84-43bc-af51-af23b00b87a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPj3']</value>
      <webElementGuid>32842db9-4e01-445d-b408-14f268bde769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3FPf3']/input</value>
      <webElementGuid>d928f7e6-1c15-40b8-8765-aedce860b23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>f799ed1b-8b53-4af3-9388-3b9f61cbe7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3FPj3' and @type = 'text' and @name = 'customer_email_update']</value>
      <webElementGuid>1f403e73-c59f-4fc7-b924-53ea787980d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
