<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , uERSl9-search, , ))_uERSl9-search</name>
   <tag></tag>
   <elementGuidId>ddcadf8f-3c04-4347-b5ed-42a9e02abdee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[ @type = 'text' and @placeholder = 'Type to search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uERSl9-search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uERSl9-search' and @type = 'text' and @placeholder = 'Type to search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5b5b090-3842-482a-a4d1-2fd074fc4f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uERSl9-search</value>
      <webElementGuid>9e5eb0f2-c8f9-4ad7-befd-00c5f61a135e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-search</value>
      <webElementGuid>ae9a3ac2-1a5b-4659-ae04-fe9998498277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93d8b7d8-3db7-458b-b0cb-d53ee3c9a0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b8ceec1c-af48-4363-8a1f-678b2326da09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to search</value>
      <webElementGuid>49d1a9f8-0e12-401a-bbc0-afbdcc7cc0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uERSl9-search&quot;)</value>
      <webElementGuid>9c3d98c2-ccaa-4e5f-a2fe-c36f3c7f838a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uERSl9-search']</value>
      <webElementGuid>0243b42b-1b81-4907-a06b-6afb926b3897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uERSl9-pp']/input</value>
      <webElementGuid>886597a8-2856-4c20-9791-51dd385ab10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>f004f684-2387-43d8-915f-bba605b0acb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uERSl9-search' and @type = 'text' and @placeholder = 'Type to search']</value>
      <webElementGuid>affab014-21b1-47f1-aa3b-0acac4db8e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
