<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tipe Pelapor_sQjFp1-icon</name>
   <tag></tag>
   <elementGuidId>c8b44ae6-0a86-499e-8b36-b71236542f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sQjFp1-icon' and @class = 'z-combobox-icon z-icon-caret-down']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sQjFp1-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@class='z-combobox-icon z-icon-caret-down']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a97ea9b0-b8a3-4c96-ba50-bc632a8e7fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sQjFp1-icon</value>
      <webElementGuid>4336d963-0318-4987-9c5e-63fe3c419836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-icon z-icon-caret-down</value>
      <webElementGuid>17c3fd89-cc2a-4f15-b487-81044d8384e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sQjFp1-icon&quot;)</value>
      <webElementGuid>ed376eb1-0fe3-4887-a122-8857a48b0a11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='sQjFp1-icon']</value>
      <webElementGuid>888642e4-e71f-4e80-9d27-84afbf434822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sQjFp1-btn']/i</value>
      <webElementGuid>cc79a68c-fa88-4b1a-a21b-4e689cc05ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/i</value>
      <webElementGuid>df0716e2-fdfe-4ac4-a9ea-e298df3ad58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'sQjFp1-icon']</value>
      <webElementGuid>dd54b511-a04e-4dad-b07a-6db9d123bc07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
