<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No.Kontrak</name>
   <tag></tag>
   <elementGuidId>3c7d09fd-1f6a-455a-b5fe-befbc5f29dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'No. Kontrak' or . = 'No. Kontrak')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rO3Sr1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a03fae49-5212-4c12-ac3e-2b917b4c2775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rO3Sr1</value>
      <webElementGuid>e23bf6d7-179e-49b6-9f53-4d87c434fd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem z-comboitem-selected</value>
      <webElementGuid>834d5157-87b5-44f3-ac20-6d206c3b2bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No. Kontrak</value>
      <webElementGuid>504824a7-35eb-4ab1-8a81-30d99f35ed73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rO3Sr1&quot;)</value>
      <webElementGuid>11222eed-0236-44e5-aa7b-05261821c642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='rO3Sr1']</value>
      <webElementGuid>6e1b001d-dca0-4fff-a409-70434fffa735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rO3Sp1-cave']/li[2]</value>
      <webElementGuid>e8e646cc-5e4a-4681-a147-8eb23c2ed7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[4]/following::li[1]</value>
      <webElementGuid>53fc111e-0d34-4057-a94e-034b312f9428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]</value>
      <webElementGuid>376e6752-bacb-4316-a96a-dde26f96ae17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'rO3Sr1' and (text() = 'No. Kontrak' or . = 'No. Kontrak')]</value>
      <webElementGuid>dd1665e5-dbad-4c5f-8519-cc01413f8d5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
