<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_update_phone_number_update</name>
   <tag></tag>
   <elementGuidId>0d801c29-5c01-4db9-8a0f-0ad6c9898dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number' and @name = 'phone_number_update']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3FPb3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22af83cf-615f-44f0-a2d2-350859f289d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPb3</value>
      <webElementGuid>84f5570d-5913-4220-ade1-8d68cb4994b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-length required z-textbox z-textbox-hover</value>
      <webElementGuid>56eec2a1-1721-4bb7-b1ac-e18b9c9d3282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ebe14fa2-75b4-44c4-9dd7-68f371ca7807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-length</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>7cd7f6fe-808a-4063-9be2-1fe4eb036a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>a0a21c80-ccae-43e0-bd60-bb81540c1a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number_update</value>
      <webElementGuid>f80d8f2c-c160-4171-b029-cece3324676b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPb3&quot;)</value>
      <webElementGuid>3b7f3ab6-b931-45c6-b3e9-ed35ac162ae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPb3']</value>
      <webElementGuid>2ee4905e-7fe5-4f08-bba7-6c0d5bec326f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3FP73']/input</value>
      <webElementGuid>757e2bb8-0110-4f12-9bcd-7ec7b14207ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>7e161e12-7649-4532-92a4-4d7242b8ddf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3FPb3' and @type = 'number' and @name = 'phone_number_update']</value>
      <webElementGuid>fc948f5a-f01d-40e8-9173-2ba878f71317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
