<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_KTP Konsumen</name>
   <tag></tag>
   <elementGuidId>551f1908-8e55-453a-ad03-aace53aafb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[text()='KTP Konsumen*'])[1]&#xd;
</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pQNQy91-cnt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pQNQy91-cnt' and (text() = 'KTP Konsumen*' or . = 'KTP Konsumen*') and @selector = concat(&quot;(//label[text()=&quot; , &quot;'&quot; , &quot;KTP Konsumen*&quot; , &quot;'&quot; , &quot;])[1]&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e4f97d32-5ce9-4779-86c4-3cedee31b3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pQNQy91-real</value>
      <webElementGuid>951692eb-e6f6-49c3-97de-797dfe8f4b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pQNQy91-cnt</value>
      <webElementGuid>a80c3da1-57e8-4329-b7bd-1069ea1f59c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>2ebb73ed-c65c-4f55-93a9-3a68e2240994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KTP Konsumen*</value>
      <webElementGuid>d7f379bb-6edb-4f10-9d31-cd203e7b13db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pQNQy91-cnt&quot;)</value>
      <webElementGuid>75569063-6954-43fb-8175-9ca19b6daccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selector</name>
      <type>Main</type>
      <value>(//label[text()='KTP Konsumen*'])[1]</value>
      <webElementGuid>719ca029-e3f8-474b-9db5-a2ebba553630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pQNQy91-cnt']</value>
      <webElementGuid>15b9cf19-588d-4415-9da0-8b2123da18fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pQNQy91']/label</value>
      <webElementGuid>13fc7e31-ed4d-43db-8c77-ffdcad398b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Pengaduan'])[1]/following::label[1]</value>
      <webElementGuid>90775a91-eacd-45a0-9c54-a545abb84039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengerti'])[1]/following::label[1]</value>
      <webElementGuid>7b54a849-c867-4d63-a71d-10ad45f51381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan*'])[1]/preceding::label[1]</value>
      <webElementGuid>bc3facf7-4d85-43e7-b491-b8edcaaef5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KTP Konsumen*']/parent::*</value>
      <webElementGuid>63a3ee65-2057-42a8-9c30-98a795b529ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/span/span/label</value>
      <webElementGuid>999bb365-f484-457c-8518-ba641aa8e14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pQNQy91-cnt' and (text() = 'KTP Konsumen*' or . = 'KTP Konsumen*')]</value>
      <webElementGuid>be3154d0-b88f-4771-9e92-bf5bbb723dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
