<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bukti Penagihan</name>
   <tag></tag>
   <elementGuidId>4e9de282-d055-4de0-adff-ee69fd9cdd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[text()='Bukti Penagihan*'])[2]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xO8Zi31-cnt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'z-radio-content' and (text() = 'Bukti Penagihan*' or . = 'Bukti Penagihan*')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0ead81fd-2e4b-40e6-8ab3-c96e2156430a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>xO8Zi31-real</value>
      <webElementGuid>61f87cf8-8ce6-4bd2-adb1-aedb55630754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xO8Zi31-cnt</value>
      <webElementGuid>16031d09-5d84-40e8-9d00-a204a0d7fab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>ad22fe55-c683-4701-910d-6a45c8ab0e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bukti Penagihan*</value>
      <webElementGuid>2541e38b-719c-4bdc-812e-b0fe694bab8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xO8Zi31-cnt&quot;)</value>
      <webElementGuid>bc3f67ef-944a-45ff-aec3-bc79f2ac795d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='xO8Zi31-cnt']</value>
      <webElementGuid>5d0d6a6c-0c6d-426d-80c1-b8def5c90206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xO8Zi31']/label</value>
      <webElementGuid>21f5f84c-9551-4662-889a-7d06fb6aafa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP Konsumen*'])[2]/following::label[1]</value>
      <webElementGuid>65120d19-c73a-4eef-8536-20eaa2116594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revisi Dokumen'])[1]/following::label[2]</value>
      <webElementGuid>89375d1b-2dbe-4292-b73b-00f534facfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[2]/preceding::label[2]</value>
      <webElementGuid>67fbc7d3-9f2f-4bf0-8033-b510d4792824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span[2]/label</value>
      <webElementGuid>39a3eff3-e599-4dfd-a80c-813c090aa1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'xO8Zi31-cnt' and (text() = 'Bukti Penagihan*' or . = 'Bukti Penagihan*')]</value>
      <webElementGuid>bd9f34c9-b7e1-451b-bd9b-a85e29463aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
