<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_update_phone_number_update</name>
   <tag></tag>
   <elementGuidId>40fc1384-f85f-4500-871f-6c434ae01725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number' and @name = 'phone_number_update']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3FPb3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c328d8f-9628-4a3b-b25c-8957a3619a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPb3</value>
      <webElementGuid>9b9acdfa-89ff-4f57-841c-323124401e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-length required z-textbox z-textbox-hover</value>
      <webElementGuid>49a7733f-92d0-4478-8663-4d4544cbabc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5864efa5-8e5b-4000-a53b-76ad16f71555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-length</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>e9f408d0-ec9a-4b22-9ec8-5b8eb96d72a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>ad88673a-a2cc-47a6-8ffb-a2c49718fa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number_update</value>
      <webElementGuid>a7218411-0460-48e6-8429-17e5a4e983d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPb3&quot;)</value>
      <webElementGuid>b5c9ca97-2237-4f8b-a5b8-af65f1f41d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPb3']</value>
      <webElementGuid>13f8e32b-b268-456c-9029-51171b386b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3FP73']/input</value>
      <webElementGuid>266d15f2-dc5c-4bef-94b6-a839f4428128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>93ed14f1-2478-4fa2-90db-f11d199f371a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3FPb3' and @type = 'number' and @name = 'phone_number_update']</value>
      <webElementGuid>849cc6bf-83df-42a9-aef7-38fa7c137bf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
