<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_update_customer_email_update</name>
   <tag></tag>
   <elementGuidId>d529c291-f8b8-4cde-bed2-79256fdf599e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and @name = 'customer_email_update']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3FPj3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec30c560-cb96-4db5-b10b-439061077414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPj3</value>
      <webElementGuid>899d0183-b4b5-43dc-bf2a-9347190b1871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required email z-textbox z-textbox-hover</value>
      <webElementGuid>9695d3ab-f3c1-4ab0-89e3-0ea05815a8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02a16de3-7b04-493d-bc9c-ea22cb21c33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_email_update</value>
      <webElementGuid>5ff08769-3d5e-47b8-9993-b3a49f8ce35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPj3&quot;)</value>
      <webElementGuid>27ecf5dc-46d7-4b4e-ae3f-bf0ad6fadeab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPj3']</value>
      <webElementGuid>47eb9a45-2234-4984-aba9-60dd282d368c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3FPf3']/input</value>
      <webElementGuid>877f6148-5db4-4ddd-a4aa-71cbb316239a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>95f5c526-3071-47f4-9d85-af6ec1ed7f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3FPj3' and @type = 'text' and @name = 'customer_email_update']</value>
      <webElementGuid>e4862967-f110-45f1-910e-ff275e2f4bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
