<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_update_customer_email</name>
   <tag></tag>
   <elementGuidId>0d49fe74-13a7-4a29-a1a4-955aeaa47892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @name = 'update_customer_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iNEFi3-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e002fcd4-3632-4f03-969e-d47e6a9b430c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a04ba88-7d63-4f5d-8e8a-a2e6f3ac67b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iNEFi3-real</value>
      <webElementGuid>fa34f22f-3ae0-46bc-9507-725f949ced9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>update_customer_email</value>
      <webElementGuid>3ade5e70-6ee0-48cb-85ef-2ba660b95e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>839e8d56-2e65-4777-b55d-ceb5036aad6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iNEFi3-real&quot;)</value>
      <webElementGuid>36ef4fb6-43e2-4103-b2f8-0d096f745f64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iNEFi3-real']</value>
      <webElementGuid>331b0cc0-14ce-4594-baec-19ea1c0a69b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='iNEFi3']/input</value>
      <webElementGuid>fb2f64ab-5b01-4cf4-b587-25e8ddfd2ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]/input</value>
      <webElementGuid>d3d80a90-6aa2-4100-955f-96311f3fd4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'iNEFi3-real' and @name = 'update_customer_email']</value>
      <webElementGuid>f1c15cef-d5c1-46dc-ba66-bad6a78f726a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
