<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_representative_nik</name>
   <tag></tag>
   <elementGuidId>dfda94eb-6c12-4bb1-8b05-cff73e6a7773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'bBuZbh' and @type = 'number' and @name = 'representative_nik' and @placeholder = 'NIK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bBuZbh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'number' and @name = 'representative_nik' and @placeholder = 'NIK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c9caacf-32d7-4912-97b4-aa647edf9343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bBuZbh</value>
      <webElementGuid>f0e13c10-213b-407a-863a-21781a6eb596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required max-length min-length z-textbox</value>
      <webElementGuid>51fe3da1-236b-4a7f-9ae2-4c909db5db4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d0834b99-0dc0-4e40-b128-a6554ed6a24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-length</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>5762c9b2-985c-4c99-8aac-df0ff96287bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-length</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>24edd673-08aa-48a2-9a13-0a2041cbb831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>4622a961-8716-4526-8d15-5cc0e1bbff2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_nik</value>
      <webElementGuid>f2c0ca20-9f1f-4ff7-bd22-cf1bf34ea0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>cdd339e9-b330-4e98-8581-6dcf7a083098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bBuZbh&quot;)</value>
      <webElementGuid>e1a4f14d-5e5f-4c94-92e5-86e40bcef1ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bBuZbh']</value>
      <webElementGuid>5deffa7f-817b-4ce5-aba9-742366de7664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bBuZ9h']/input</value>
      <webElementGuid>e9aa8b24-3c8e-4e6e-b754-66d000a5f61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>36a2231b-1075-4908-b05f-76fa55ba1bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bBuZbh' and @type = 'number' and @name = 'representative_nik' and @placeholder = 'NIK']</value>
      <webElementGuid>50eb2dcc-820f-4653-91e7-b87b28a95a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
