<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Handphone_representative_phone</name>
   <tag></tag>
   <elementGuidId>9273673d-bfae-4faf-8639-9f472d4b6385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'bBuZqh' and @type = 'text' and @name = 'representative_phone' and @placeholder = 'No. Handphone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bBuZqh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'representative_phone' and @placeholder = 'No. Handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65a64210-3ea8-4dd6-ad4b-1c9bc8510a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bBuZqh</value>
      <webElementGuid>40cc12e5-2975-46a3-8478-b8bd3436ff8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>only-numeric max-length required z-textbox z-textbox-hover</value>
      <webElementGuid>32b00be8-ebf4-428f-b3cb-31263306e4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-length</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>57858093-eecd-4dec-8f8a-c30c0c0e681d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2186bcab-74b3-424e-923c-564d57c352f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>4b5f0dde-0a67-41bb-9be1-7be5d23c9239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_phone</value>
      <webElementGuid>989c8f92-c059-40b7-9e01-47017a7caab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Handphone</value>
      <webElementGuid>f31acf6f-d08d-4b5f-b597-62c613f3bed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bBuZqh&quot;)</value>
      <webElementGuid>ba813fd3-bcb9-4fc3-b866-94c146dc3d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bBuZqh']</value>
      <webElementGuid>5afdb997-8b38-4d64-8edb-a393322110ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bBuZoh']/input</value>
      <webElementGuid>5309bcb5-839a-492b-bfc9-c95bcf08ac9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>0a0a9034-a8a5-4819-acde-c83ae31a3882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bBuZqh' and @type = 'text' and @name = 'representative_phone' and @placeholder = 'No. Handphone']</value>
      <webElementGuid>1cbcb022-08e7-4d92-a6c3-41a49aafe5b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
