<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_representative_name</name>
   <tag></tag>
   <elementGuidId>4a706805-2c41-41be-b750-851f7d4a4d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'bBuZih' and @type = 'text' and @name = 'representative_name' and @placeholder = 'Nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bBuZih</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'representative_name' and @placeholder = 'Nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee9eda0b-c36b-47f2-bae5-8234950346e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bBuZih</value>
      <webElementGuid>d6d96287-d3e8-402b-86d7-aac8985e75db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required min-length z-textbox z-textbox-hover</value>
      <webElementGuid>04f2782c-1081-4c1f-bdec-315949469604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7daf4552-d9b3-4750-8892-dd65ba2cb6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>085950c3-eb75-4251-bb54-a172e15dc793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_name</value>
      <webElementGuid>2c3df68f-3484-415d-9f6f-373caac6ad7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>3a236f52-d7da-4a85-ac35-efcea0e1e136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bBuZih&quot;)</value>
      <webElementGuid>0feee79f-06f2-4f35-a9f0-8ce87fb7c9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bBuZih']</value>
      <webElementGuid>308e5944-91cb-442d-be17-cdb595786d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bBuZgh']/input</value>
      <webElementGuid>0a3cac50-2ad3-485d-9a64-868326a67164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>3b28361b-efa2-4664-b08c-ec725835c3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bBuZih' and @type = 'text' and @name = 'representative_name' and @placeholder = 'Nama']</value>
      <webElementGuid>51cf89d1-5252-4b65-9cee-0fa5db7b393e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
