<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_representative_email</name>
   <tag></tag>
   <elementGuidId>ab4f87ac-1073-4677-8171-58b8396a38bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'bBuZwh' and @type = 'text' and @name = 'representative_email' and @placeholder = 'Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bBuZwh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'representative_email' and @placeholder = 'Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b555e7a-05c1-4bc7-88be-58fcc0b6054a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bBuZwh</value>
      <webElementGuid>14367260-b88d-4e29-bd86-e7d2b8dc2c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required email z-textbox z-textbox-hover</value>
      <webElementGuid>0c95c08b-b052-4470-90b3-3832bc155718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>696d5d08-6c7f-461f-9adf-ad603ad8774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_email</value>
      <webElementGuid>0d226bbc-7da0-4b2f-8b72-9ddfca718c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>f5ad8e69-cddb-4dba-8ae9-c4e46c21d7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bBuZwh&quot;)</value>
      <webElementGuid>a77833b4-e923-406a-b619-dd9de098e10e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bBuZwh']</value>
      <webElementGuid>4bb2ea66-0795-4cb9-8b03-e6a86b6e2a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bBuZuh']/input</value>
      <webElementGuid>99d08e6d-daa8-4d79-9a39-f24f5662c77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>f55d44d2-aaf3-42fe-9236-b13463108018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bBuZwh' and @type = 'text' and @name = 'representative_email' and @placeholder = 'Email']</value>
      <webElementGuid>3f819288-0ee7-4220-92fb-f3d3300e4301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
