<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari</name>
   <tag></tag>
   <elementGuidId>3f454488-bfab-4c7b-85a2-46abcb69982c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sQjFg2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button' and text()='Cari']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9d1eb06-0afa-4d12-974d-1fd35cf14278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77ca70c2-1e35-42a5-95b7-e64ac00dadd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sQjFg2</value>
      <webElementGuid>3b784d68-026c-4ed1-ba26-3f74232075ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-width btn-primary btnSearch z-button</value>
      <webElementGuid>9cb0e74f-883c-46e4-a3ba-fa919a3aa665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>04986dd8-b4d9-47ac-b224-7d4c5279ba93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sQjFg2&quot;)</value>
      <webElementGuid>eb50fc57-9e54-432c-bcc4-c481c9c9d960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sQjFg2']</value>
      <webElementGuid>f22dd27d-427a-4f7c-a618-cf0bc2ed32e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sQjFf2']/button</value>
      <webElementGuid>fe188342-13b0-4236-a6cd-15adc64559f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak Pengaduan'])[1]/following::button[1]</value>
      <webElementGuid>0686d65f-83e1-4789-915e-0b3b6de5a712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/following::button[2]</value>
      <webElementGuid>b822bc48-9130-42ea-a6d5-8fc4dbedd064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pengajuan Pengaduan Data Konsumen'])[1]/preceding::button[1]</value>
      <webElementGuid>11843a42-a47d-4f18-9fcd-8eb44d89c3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lengkap Sesuai KTP'])[1]/preceding::button[2]</value>
      <webElementGuid>c8bb16d8-f772-4654-b5f0-0beb061277f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>c5f02a73-7086-44a7-82ce-314d6a76401e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/button</value>
      <webElementGuid>00aee82e-cf97-48ee-9d6d-84b8e9741ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'sQjFg2' and (text() = 'Cari' or . = 'Cari')]</value>
      <webElementGuid>1249f800-1b53-4e19-94aa-776212f005e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='zOgEg2']</value>
      <webElementGuid>147aefa2-831e-408b-b3e4-85a4169ad3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zOgEf2']/button</value>
      <webElementGuid>cc935b38-89cc-4223-b77c-6a0c35220329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'zOgEg2' and (text() = 'Cari' or . = 'Cari')]</value>
      <webElementGuid>4421ff4d-72b2-4f2a-a4d4-a6ed23d252cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
