<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_representative_email</name>
   <tag></tag>
   <elementGuidId>829a0c7c-9dd7-41e0-8ad8-3ad9240a2c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wZBV02</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'wZBV02' and @type = 'text' and @name = 'representative_email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'representative_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>083b01d8-7d42-4654-bc53-ad1d8685d71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wZBV02</value>
      <webElementGuid>1bbd7f24-5fe8-4a45-9cce-8b1af459995a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required email z-textbox z-textbox-hover</value>
      <webElementGuid>64c017e6-6d58-4bdd-99dc-ec79e79e3674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e365ca3a-bf94-48de-a3a1-fb263c6f8816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_email</value>
      <webElementGuid>f078b802-95d4-4e62-a57b-52f99de76c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wZBV02&quot;)</value>
      <webElementGuid>036bbbef-fbee-4d8d-a3d5-8f69942bc2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wZBV02']</value>
      <webElementGuid>e28a0b6e-3f4f-416d-87ad-4f8b23ca6e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wZBVz1']/input</value>
      <webElementGuid>529ffec4-72d3-4449-b6ef-a8fdf2857f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>a72db7c0-f351-450f-b148-3d74e5b0535b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wZBV02' and @type = 'text' and @name = 'representative_email']</value>
      <webElementGuid>d8320cf2-67ab-4968-9339-487ead36b210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
