<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Handphone_representative_phone</name>
   <tag></tag>
   <elementGuidId>ff9bb729-1370-4e73-b777-d8f1e5b9fdff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wZBV72</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'wZBV72' and @type = 'number' and @name = 'representative_phone']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'number' and @name = 'representative_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70a8b676-786a-425f-96c0-d5c8d7718c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wZBV72</value>
      <webElementGuid>65a2f0c8-7ae8-416a-8c47-e866514270b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required only-numeric max-length min-length phone-input z-textbox</value>
      <webElementGuid>2e538ef3-d5d0-4cc8-ba61-6da98d5e101d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>ccbf052e-5ea1-4107-b3f4-053c32017bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c512b9bd-2d80-48d2-9c4c-b4da64641d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8154c295-302b-48bd-ac45-a9ffcf2d58eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlengthmessage</name>
      <type>Main</type>
      <value>Silakan masukkan minimal 10 karakter</value>
      <webElementGuid>84158976-8b2e-4a21-80fd-5d305e17ef6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_phone</value>
      <webElementGuid>b30167bb-7cea-4bdb-96f2-f88c7f48e2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wZBV72&quot;)</value>
      <webElementGuid>c4292063-bbb6-4424-9856-f1e888e1aa1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wZBV72']</value>
      <webElementGuid>b44dc671-006a-460a-8fb3-9295692ef4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wZBV52']/input</value>
      <webElementGuid>8c649b71-ec0d-44fc-be62-cc3beb283507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f9599ccc-8624-4134-affc-ce4770a1d15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wZBV72' and @type = 'number' and @name = 'representative_phone']</value>
      <webElementGuid>221e17e3-f1f8-4ef8-a66e-1cb76491f281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
