<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_representative_name</name>
   <tag></tag>
   <elementGuidId>73cfb0c3-7983-4de5-bec7-819147b34350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wZBVw1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'wZBVw1' and @type = 'text' and @name = 'representative_name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'representative_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce406998-5e56-4488-8271-e15aec8ea43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wZBVw1</value>
      <webElementGuid>e76c9bb8-e37c-4dee-a3df-c1e562fa8d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required min-length z-textbox z-textbox-hover</value>
      <webElementGuid>6d0fa3bf-7d96-4b04-a953-2fe2428ecf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>590e6484-94ee-4a80-9a40-246f42b9f640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlengthmessage</name>
      <type>Main</type>
      <value>Silakan masukkan minimal 3 karakter</value>
      <webElementGuid>d83a8802-0a69-4f79-8ffa-c4f588bf9905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebb9d3ea-eeb6-4dae-a817-c35a75f4fd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c806317f-4727-4da2-a289-766b59efc78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_name</value>
      <webElementGuid>be96a7fd-d21d-42f7-9ad3-e27a016b4b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wZBVw1&quot;)</value>
      <webElementGuid>a31c859f-dad7-4441-aa13-ba28a26f0a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wZBVw1']</value>
      <webElementGuid>4be5bef3-a89b-4cd9-8cad-cb1422957465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wZBVu1']/input</value>
      <webElementGuid>2b4b8fac-bdec-466a-9143-7e8698a8352d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>682586df-5c75-40a6-a2ed-e74f2f353500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wZBVw1' and @type = 'text' and @name = 'representative_name']</value>
      <webElementGuid>364a8e73-e2d4-421d-bd43-66a94fa81838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
