<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_representative_nik</name>
   <tag></tag>
   <elementGuidId>287782bf-0e08-44e3-bb23-5a8aa3c088f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wZBVq1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'wZBVq1' and @type = 'number' and @name = 'representative_nik' and @placeholder = 'NIK']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'number' and @name = 'representative_nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cfdc987-0592-4e75-bd94-cb069b14105f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wZBVq1</value>
      <webElementGuid>1180a6a0-279f-43cb-b9aa-2906a726b129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required max-length nik-length z-textbox z-textbox-hover</value>
      <webElementGuid>27bd4c5f-e3ea-49b6-8803-b9d8c22798da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c70f4f05-5c2a-4d36-a2ce-66cbf739aadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-length</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>0d95fc40-dee9-47ee-a296-7e49cbce2e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>niklengthmessage</name>
      <type>Main</type>
      <value>Silakan masukkan 16 digit NIK</value>
      <webElementGuid>58070aef-fad9-45f1-9bc3-0403bd6c7795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c48d773e-c291-4303-a69b-e58870d53c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>representative_nik</value>
      <webElementGuid>d5daa120-edeb-44f7-9bf1-3e8eda498834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>cf808729-9ecb-4026-a97c-3042ea41c432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wZBVq1&quot;)</value>
      <webElementGuid>b403f41d-e0ee-4cb6-90b5-b72158bd58c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wZBVq1']</value>
      <webElementGuid>3b88d4fe-5abf-4fb5-98f5-24ba5608c1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wZBVo1']/input</value>
      <webElementGuid>24cfaf2f-7412-468a-8cfd-88e7322a6780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>052f86b0-2a31-4268-bbb5-b4a1d5692a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wZBVq1' and @type = 'number' and @name = 'representative_nik' and @placeholder = 'NIK']</value>
      <webElementGuid>2c66a46f-888b-433d-bb7a-35473406e8c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
