<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No.Kontrak</name>
   <tag></tag>
   <elementGuidId>fc1b3b73-3637-4a5e-91d4-8c0569da82c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rO3Sr1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'No. Kontrak' or . = 'No. Kontrak')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>03ed0d4d-2f7e-4f98-92f6-dbe5faea1b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rO3Sr1</value>
      <webElementGuid>1b530435-38dd-42d1-82bc-cbfb93369b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem z-comboitem-selected</value>
      <webElementGuid>ee002637-b2d6-4c68-96b7-615c4e35dab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No. Kontrak</value>
      <webElementGuid>1be7ed47-dd0f-497c-b46e-51a8887b0f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rO3Sr1&quot;)</value>
      <webElementGuid>31574857-6e02-45bd-9802-ef7dc3eb0c13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='rO3Sr1']</value>
      <webElementGuid>e050439a-771b-4fb4-963d-dcaecce9e96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rO3Sp1-cave']/li[2]</value>
      <webElementGuid>06edc010-6331-470e-971c-a847f9de2c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[4]/following::li[1]</value>
      <webElementGuid>312f28f9-4557-47a8-9241-2fd464658686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]</value>
      <webElementGuid>e7984a10-4652-4986-9ad3-9f229adee86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'rO3Sr1' and (text() = 'No. Kontrak' or . = 'No. Kontrak')]</value>
      <webElementGuid>be72dc57-2372-4e44-96bc-d6714bec9e59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
