<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tambah Baru</name>
   <tag></tag>
   <elementGuidId>7c4c51c7-c847-4705-b04b-48b4645a06fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Tambah Baru' or . = 'Tambah Baru')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.z-menu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Tambah Baru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6abc4e37-e7e9-4cab-8352-6ffcd90e01e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-menu-text</value>
      <webElementGuid>1ec9f65a-2dc8-43a5-bb86-9d9b5bda0387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Baru</value>
      <webElementGuid>ca981dc2-2487-4895-89f8-5f2cf8e2b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r9ARc3-a&quot;)/span[@class=&quot;z-menu-text&quot;]</value>
      <webElementGuid>a62bd58d-5781-4444-a179-e39e242df600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='r9ARc3-a']/span</value>
      <webElementGuid>c2b1e300-0dc1-4989-90ab-54d1840bef8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Penerimaan'])[3]/following::span[2]</value>
      <webElementGuid>0cbcc592-041a-40a9-b3a7-0f560891d79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::span[2]</value>
      <webElementGuid>910d3d5e-a4c0-4728-be42-c0fbcf8d7398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::span[2]</value>
      <webElementGuid>09abe501-0e42-46e6-8402-a51ea7c334ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[1]/preceding::span[2]</value>
      <webElementGuid>17d9fec0-1c10-4945-86fa-0f4a476d3c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Baru']/parent::*</value>
      <webElementGuid>61c0ad58-8744-4d00-8c55-9e658e23f94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/span</value>
      <webElementGuid>f62f92d3-9c27-4bc7-a6b9-44a9a59e131b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tambah Baru' or . = 'Tambah Baru')]</value>
      <webElementGuid>8e0eab7b-4112-4f7d-b352-27e6a765aef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
