<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Konsumen</name>
   <tag></tag>
   <elementGuidId>0678a08c-e758-4a2c-8b39-e33fdac5c177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Konsumen' or . = 'Konsumen')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.z-menuitem-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Konsumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e6aa7f6-c398-45c0-93fc-1df0b3d4eea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-menuitem-text</value>
      <webElementGuid>45b15766-5ffc-4863-80aa-ddd147ce3385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konsumen</value>
      <webElementGuid>0c6b497b-d4ee-4d5b-97ae-84ff967f5f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t1ZLe3-a&quot;)/span[@class=&quot;z-menuitem-text&quot;]</value>
      <webElementGuid>61c124f4-004d-48f1-9231-435d47da081a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='t1ZLe3-a']/span</value>
      <webElementGuid>7640f0fa-5802-494f-aed6-f01a4c91528c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[1]</value>
      <webElementGuid>32dc82bc-ebb2-4435-9537-c9010186f77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perwakilan Konsumen'])[2]/preceding::span[1]</value>
      <webElementGuid>0cb5c198-89cd-4238-a0f4-ce9d03a06199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Konsumen'])[2]/preceding::span[2]</value>
      <webElementGuid>0c6c5711-dae0-45e4-950e-dc8429697697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a/span</value>
      <webElementGuid>a1097b9c-5f7d-4cde-af19-98a5cdf499bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Konsumen' or . = 'Konsumen')]</value>
      <webElementGuid>ffc8d2b5-b58f-4966-a2ce-dd6f57a3005c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
