<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Belum ada sub category yang dipilih_uERSl9-placeholder</name>
   <tag></tag>
   <elementGuidId>f559fc8e-66e0-49a3-8b91-3370feb7cca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uERSl9-placeholder' and @class = 'z-searchbox-placeholder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uERSl9-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'z-searchbox-placeholder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f189f3ca-14f2-4335-a857-f4ac05ba80ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uERSl9-placeholder</value>
      <webElementGuid>390df507-38f9-42a1-a9f3-e7d74022a866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-placeholder</value>
      <webElementGuid>19c034c3-0848-431b-ad47-38224fea1c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uERSl9-placeholder&quot;)</value>
      <webElementGuid>859fc2b3-d1cf-4b43-bebc-3cc4cdc42dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uERSl9-placeholder']</value>
      <webElementGuid>a1d0fdbd-9fda-417a-820c-a571a2eed358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uERSl9']/div[2]</value>
      <webElementGuid>8e4ba6d6-45db-4985-8598-4545d7052df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>8c517b2e-6679-41a2-8dfd-7e3c805bef58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uERSl9-placeholder']</value>
      <webElementGuid>33c6adcd-0a62-4726-996b-80a01d75c50e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
