<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , uERSl9-search, , ))_uERSl9-search</name>
   <tag></tag>
   <elementGuidId>cda0fe92-5131-4dfa-b643-d1fcdc139e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uERSl9-search' and @type = 'text' and @placeholder = 'Type to search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uERSl9-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[ @type = 'text' and @placeholder = 'Type to search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd359845-d19c-49a0-ba39-f902c21ef284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uERSl9-search</value>
      <webElementGuid>6cd31c91-d59f-46c5-9d07-8fa18aec51bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-searchbox-search</value>
      <webElementGuid>cb6aa436-0de3-4308-b464-04289fc8bc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9778b726-c3fe-4faf-8caf-d798c2b1cdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f13698af-295f-47a3-8235-bec51457a059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to search</value>
      <webElementGuid>170e8622-56ba-4187-9ec6-a23a32cccc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uERSl9-search&quot;)</value>
      <webElementGuid>52a3e7d3-fb32-4fd2-b451-233326f0c526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uERSl9-search']</value>
      <webElementGuid>9e3980dd-74a8-4c22-9248-5d5dd64796cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uERSl9-pp']/input</value>
      <webElementGuid>ac156d79-33c9-47ab-afce-f6d06f5df2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>50e87856-5d25-491c-a508-7e156cd2f6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uERSl9-search' and @type = 'text' and @placeholder = 'Type to search']</value>
      <webElementGuid>5d63d7eb-477d-4bd0-8bfd-1a83c0329d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
