<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No.Kontrak_search_value</name>
   <tag></tag>
   <elementGuidId>54c15bfb-ef58-4eae-8f1b-e32795cb8632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sQjFs1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sQjFs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cd11376-ae5b-49a2-8598-ef3264b8cf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sQjFs1</value>
      <webElementGuid>4c04d5fb-8a13-463c-b2ab-d86fdb9640a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-mt-0-3 max-length required only-numeric z-textbox z-textbox-hover</value>
      <webElementGuid>6b32c126-ac0e-4dcb-8624-ecafcf4e7ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43946f30-2104-4ddc-a659-f0642cb027b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>301f0ae8-4759-42b7-a0b7-52d3f31b6cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_value</value>
      <webElementGuid>9ee96104-78d3-42e3-8d38-9d66a6d73c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Kontrak</value>
      <webElementGuid>fc79038e-e3e9-40ab-a03d-1051d60ffa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sQjFs1&quot;)</value>
      <webElementGuid>59a72fb7-843a-45d8-a2d1-a0c69d719e93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sQjFs1']</value>
      <webElementGuid>bc659c59-4997-475e-aec9-fed4b02299f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sQjFo1']/input</value>
      <webElementGuid>30154e3a-a96a-46f9-b96f-56611460bd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bfd2c898-6eda-4868-b99b-b38bdbcd8e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sQjFs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      <webElementGuid>b93fec6b-598c-4889-aacc-fa057b340357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zOgEs1']</value>
      <webElementGuid>1f36d784-a754-498b-80c5-5efc2e965ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zOgEo1']/input</value>
      <webElementGuid>e935b00d-338e-4471-bc46-c6b8a99aaaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zOgEs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      <webElementGuid>931cb950-23f0-4902-9725-bf2966d8b404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
