<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Pengaduan Konsumen Minimal 400 Karakter tidak termasuk tanda baca_detail_complaint</name>
   <tag></tag>
   <elementGuidId>83346bb3-b940-4176-8090-6ebbe1759bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pQNQ4d</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pQNQ4d' and @class = 'required min-length z-textbox z-textbox-hover' and @dependon = 'detail_complaint' and @name = 'detail_complaint' and @rows = '5']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name, 'detail_complaint')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>04246537-a80e-460d-82d7-f97042428fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pQNQ4d</value>
      <webElementGuid>708d6673-60d2-4cff-9505-eca8eb07d485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required min-length z-textbox z-textbox-hover</value>
      <webElementGuid>4af34efb-ada6-4465-8297-8b688859477a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependon</name>
      <type>Main</type>
      <value>detail_complaint</value>
      <webElementGuid>4c3b9e75-5046-42ea-a0e8-88c20f4f565f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-length</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>50af42f2-833b-43e1-b847-025a763aeb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detail_complaint</value>
      <webElementGuid>a717306a-2f57-438d-b041-a05aaf7b995d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8f3445db-c023-4c82-90ff-64a7f591ca67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pQNQ4d&quot;)</value>
      <webElementGuid>3c46b13f-2f93-4fcb-9ebf-9bb1b33c5c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pQNQ4d']</value>
      <webElementGuid>42eb0e1c-1b86-4d99-8161-98c768bd8448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pQNQ0d']/textarea</value>
      <webElementGuid>bda5f1cb-71cf-4b9a-922a-b77602bce175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/textarea</value>
      <webElementGuid>d03b3ee4-526f-444e-b248-d14349c64025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pQNQ4d' and @name = 'detail_complaint']</value>
      <webElementGuid>bf14634c-438d-411d-83ad-d5d38ac18217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
