<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>fb63dd0a-8087-4177-991f-56bc10692632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'u0YWya' and @class = 'btn-primary full-width approve-case z-button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class = 'btn-primary full-width approve-case z-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u0YWya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13289dea-109b-433c-bd07-cb7c7c75660f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09815623-f511-4e6e-a010-c5a3b5f6dec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u0YWya</value>
      <webElementGuid>9d7bae23-19bb-426c-9942-f809487d7d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary full-width approve-case z-button</value>
      <webElementGuid>49b1ffea-ce17-4fca-90a0-d3381843d8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>0a28a9d3-48d6-4003-be99-c1f2cbfac4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u0YW7&quot;)/div[@id=&quot;u0YWta&quot;]/div[@id=&quot;u0YWwa&quot;]/button[@id=&quot;u0YWya&quot;]</value>
      <webElementGuid>b7eddf10-f670-4d3f-bba5-5a5323e56ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u0YWya']</value>
      <webElementGuid>be637ae2-fa87-40d9-947c-67f443561bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u0YWwa']/button[2]</value>
      <webElementGuid>61eb039b-30a1-430a-b7d4-3d985feb303c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::button[1]</value>
      <webElementGuid>179d7746-81b1-4094-843e-66047e081e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[2]</value>
      <webElementGuid>f7106c92-3a3b-4caa-ac6a-e057bea62388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter &amp; Sort'])[1]/preceding::button[1]</value>
      <webElementGuid>7c8b6068-1201-4e49-b6a4-c9eb311dd2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/preceding::button[1]</value>
      <webElementGuid>72281d47-0390-4dcf-a34d-ac4b960ab5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9294d6f9-3e8f-4f11-a104-230be10c4526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'u0YWya' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>afc01fd3-b58b-4b25-9844-24519802fe31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
