<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No.Kontrak_search_value</name>
   <tag></tag>
   <elementGuidId>2fcee22f-55c2-4ecc-a61b-d13e781ef0ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sQjFs1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sQjFs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be749383-0d40-4154-a482-d512b5c55938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sQjFs1</value>
      <webElementGuid>ebf55dbe-2b2a-4578-b47c-56431800998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-mt-0-3 max-length required only-numeric z-textbox z-textbox-hover</value>
      <webElementGuid>ac768fb2-e4f8-42ad-accc-097d2c797144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22bf5825-4e9b-4234-b695-dff202621abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>e5e8ddd2-f6d9-4403-82b8-d1c538e5e28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_value</value>
      <webElementGuid>b8834462-cd6c-4733-ac95-882401563c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Kontrak</value>
      <webElementGuid>94a2b072-fbdf-4b00-9d41-20f601ba0ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sQjFs1&quot;)</value>
      <webElementGuid>1ae68c8f-de21-41bd-b4b6-f9553bf5a68e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sQjFs1']</value>
      <webElementGuid>b2cde9ab-c029-4376-862b-631b79b156ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sQjFo1']/input</value>
      <webElementGuid>0dd058e8-a1c0-4d2a-95e6-869361d18b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8795e643-ace9-437b-9775-571cc6db279d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sQjFs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      <webElementGuid>172be18b-88e5-48e1-beb6-a2ee21d135b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zOgEs1']</value>
      <webElementGuid>deccf674-f875-47ea-8556-f27d63e487ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zOgEo1']/input</value>
      <webElementGuid>51533ad4-8eef-4561-be54-b0ea9357a050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zOgEs1' and @type = 'text' and @name = 'search_value' and @placeholder = 'No. Kontrak']</value>
      <webElementGuid>d1b90c1b-36ac-419b-a00d-cd983bda9253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
