<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Pengaduan Konsumen Minimal 400 Karakter tidak termasuk tanda baca_detail_complaint</name>
   <tag></tag>
   <elementGuidId>0120ec6b-9dba-4d6e-9ae4-1694431662f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name, 'detail_complaint')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pQNQ4d</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'pQNQ4d' and @class = 'required min-length z-textbox z-textbox-hover' and @dependon = 'detail_complaint' and @name = 'detail_complaint' and @rows = '5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>13264961-6399-4bad-aba5-86c5725f1791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pQNQ4d</value>
      <webElementGuid>e4aa774b-b026-4de9-b119-ec70b4656433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required min-length z-textbox z-textbox-hover</value>
      <webElementGuid>a6b07835-90de-4177-9561-4264f200fcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependon</name>
      <type>Main</type>
      <value>detail_complaint</value>
      <webElementGuid>9e87e810-f916-4597-b0b5-df248773fdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-length</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>9021aae7-0408-4216-825b-cf4d4a873546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detail_complaint</value>
      <webElementGuid>49d86221-512c-48bb-9b1f-994c2a542380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a3a0b3a6-368b-4095-86ab-578310e534b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pQNQ4d&quot;)</value>
      <webElementGuid>2ed8c88f-ab5d-4b0b-adfe-a4541a6b2462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pQNQ4d']</value>
      <webElementGuid>62c4f83b-20a2-49b5-a828-0aa4d23f0677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pQNQ0d']/textarea</value>
      <webElementGuid>8c5e4bb8-6346-4a21-b767-bc3713d7b351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/textarea</value>
      <webElementGuid>4eb25475-0f6c-4d4c-8378-de199a79fcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pQNQ4d' and @name = 'detail_complaint']</value>
      <webElementGuid>3e2399a5-b484-4318-90da-f3a4ea24a643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
