<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Konsumen</name>
   <tag></tag>
   <elementGuidId>42da48d5-fa11-458b-915b-d95f2e9361f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Konsumen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.z-menuitem-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c6bde8a-7730-4dab-b604-373ccad883ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-menuitem-text</value>
      <webElementGuid>4a4ba128-2152-464f-bd35-3432d6f1ceb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konsumen</value>
      <webElementGuid>f5248b8f-a3fc-4355-bfb0-4de97666c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t1ZLe3-a&quot;)/span[@class=&quot;z-menuitem-text&quot;]</value>
      <webElementGuid>3c59275e-0370-413b-851a-4429cf8f4b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='t1ZLe3-a']/span</value>
      <webElementGuid>d9253c8d-9eea-4e00-9e42-a4094a9bfb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[1]</value>
      <webElementGuid>916193bf-35ff-45f3-a116-9b78bf890cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perwakilan Konsumen'])[2]/preceding::span[1]</value>
      <webElementGuid>cb0a9c74-f9e0-4456-9b83-2d90c7ab6fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Konsumen'])[2]/preceding::span[2]</value>
      <webElementGuid>979770b8-21e8-4828-b03b-d0c69e782bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a/span</value>
      <webElementGuid>c8929f3e-8b89-4325-bc21-effb4ef1a777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Konsumen' or . = 'Konsumen')]</value>
      <webElementGuid>1d963ff9-1015-4ccb-bdc1-0ba84d89415c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
