<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_update_customer_email_update</name>
   <tag></tag>
   <elementGuidId>7342e3a7-0a80-4300-b075-c3cd446db8d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and @name = 'customer_email_update']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3FPj3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c158800-2f35-4780-afe0-60560398637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3FPj3</value>
      <webElementGuid>c1cc097b-3567-48df-86f1-5ef324e5c1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required email z-textbox z-textbox-hover</value>
      <webElementGuid>a2e9289b-0921-4b66-866f-235161b755ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33d5536b-69d0-4528-9e84-d4db64b40491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_email_update</value>
      <webElementGuid>9070e1b7-937c-4db2-9260-10ee2fbf11be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3FPj3&quot;)</value>
      <webElementGuid>c5f0baef-fef5-4134-b820-a3ac3e89df84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3FPj3']</value>
      <webElementGuid>f9303347-4423-4fe8-b1f3-e174fdc28f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3FPf3']/input</value>
      <webElementGuid>5020b9b6-801b-4e9c-a4d8-1a1107ba343a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>19e1be96-d1b0-4063-be98-299e5b014ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3FPj3' and @type = 'text' and @name = 'customer_email_update']</value>
      <webElementGuid>25719158-69c5-4a0c-9052-7ae8226b73b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
