<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah (1)</name>
   <tag></tag>
   <elementGuidId>ca9785a4-075b-4101-b387-1ade420185b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aDjOyi1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'aDjOyi1' and (text() = 'Unggah' or . = 'Unggah')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='aDjOyi1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b43dd2b-49fa-4ab0-9bf1-057b24c2ee33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a900039-3070-4926-a861-9d6b4649b8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aDjOyi1</value>
      <webElementGuid>7af2c95d-ed04-4346-bb6d-df8307838661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-4 btn-upload z-button</value>
      <webElementGuid>6b9abaf5-eb91-4abe-a803-22d3cdaa19cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>75f0c0c4-49f7-4e36-b613-b7774b791d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aDjOyi1&quot;)</value>
      <webElementGuid>1bf70c70-6ca4-41fb-9246-c1d2f67e111c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='aDjOyi1']</value>
      <webElementGuid>8d42bc67-237c-4ba6-973d-81544d4e5e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aDjOxi1']/button</value>
      <webElementGuid>fb69f238-054f-46d3-aa2a-1704416bff23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/following::button[2]</value>
      <webElementGuid>f010d626-04f3-43d1-990c-19abafe099b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/following::button[2]</value>
      <webElementGuid>bde8d69a-e1d8-4747-a254-174a3dec65ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Template'])[1]/preceding::button[1]</value>
      <webElementGuid>9743ac1d-ad32-4beb-910e-f28f7931eccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan upload dan cek tipe dokumen terlebih dahulu'])[1]/preceding::button[2]</value>
      <webElementGuid>cf7e53a3-561c-48d3-bb05-c1d6c9924f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah']/parent::*</value>
      <webElementGuid>edbe4d59-1f21-4e2d-8aec-221cd5baff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/button</value>
      <webElementGuid>5ceb68b5-7a25-4109-b14a-0154d0e4c994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'aDjOyi1' and (text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>5dbc7d52-c661-466c-a19f-db48a11d84b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
