<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unggah</name>
   <tag></tag>
   <elementGuidId>23b4196d-0854-421a-8cf8-4a8139af52d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aDjOxi1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aDjOxi1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5dca0fb-14ed-43ff-9e34-dc3429eca043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aDjOxi1</value>
      <webElementGuid>4efc3a78-f063-4b31-94b1-01d93b732887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 px-0 col-xs-12 document-button z-div</value>
      <webElementGuid>8e027765-9dda-4f1f-ab54-183491f928ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unggah</value>
      <webElementGuid>2798d03f-d38f-4e90-a87c-b861b06edffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aDjOxi1&quot;)</value>
      <webElementGuid>11bd5280-83a2-4f42-a618-93aa3f738801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aDjOxi1']</value>
      <webElementGuid>810c29c5-da55-431e-a9d5-7fab8a8c1633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aDjOwi1']/div</value>
      <webElementGuid>c72ff90b-e1ad-45f2-a15f-d78eec16413f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/following::div[3]</value>
      <webElementGuid>3437f699-b043-4cf8-9a92-8fddb3e8a71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/following::div[5]</value>
      <webElementGuid>75468ce8-b16b-4340-80b6-115d6a963ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Template'])[1]/preceding::div[2]</value>
      <webElementGuid>89ec6a92-6011-4745-b127-5eda45f01548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[3]/div/div</value>
      <webElementGuid>7a126d1e-fbe7-429c-9fac-08f30048bb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aDjOxi1' and (text() = ' Unggah' or . = ' Unggah')]</value>
      <webElementGuid>1ddc5ca3-8e95-4a68-a847-ec0f00fafb4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
