<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bukti Penagihan</name>
   <tag></tag>
   <elementGuidId>9ea341ea-ee2b-45d2-a01e-82e1cfa1d5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xO8Zi31-cnt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'z-radio-content' and (text() = 'Bukti Penagihan*' or . = 'Bukti Penagihan*')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[text()='Bukti Penagihan*'])[3]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7c39c4b6-eff8-4555-aa57-cbef37cc37dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>xO8Zi31-real</value>
      <webElementGuid>f521b626-b6ce-4e4a-9d92-57d597794413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xO8Zi31-cnt</value>
      <webElementGuid>6bd29c6a-4c86-4cfd-a8c7-7c26f98dca95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>13decffe-d103-4ccb-bd8d-3ab3a488ae1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bukti Penagihan*</value>
      <webElementGuid>46eaa0c4-6154-440c-9cea-28b1294fd512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xO8Zi31-cnt&quot;)</value>
      <webElementGuid>98726be2-3199-4bdc-8f00-c09bfcfcfbe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='xO8Zi31-cnt']</value>
      <webElementGuid>927f941e-9031-440a-9b2b-320fbdc36d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xO8Zi31']/label</value>
      <webElementGuid>3c649f4f-74b8-4b77-9053-676586a8127b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP Konsumen*'])[2]/following::label[1]</value>
      <webElementGuid>547ab341-6506-46e2-8970-428581e02244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revisi Dokumen'])[1]/following::label[2]</value>
      <webElementGuid>0528bc54-6c4b-4dfe-80d6-002260d98e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[2]/preceding::label[2]</value>
      <webElementGuid>f0fd9d73-8967-469f-a35a-48a48f30c953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span[2]/label</value>
      <webElementGuid>f2e68287-c1ec-4d8e-a9f9-fa50e5ccaa09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'xO8Zi31-cnt' and (text() = 'Bukti Penagihan*' or . = 'Bukti Penagihan*')]</value>
      <webElementGuid>2e553a63-3bf9-40a3-b95b-ad0a40f5f6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
