<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Surat Kuasa</name>
   <tag></tag>
   <elementGuidId>fca27bf3-61e7-4370-9f09-99727b81636d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p3iIos1-cnt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'p3iIos1-cnt' and (text() = 'Surat Kuasa*' or . = 'Surat Kuasa*')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[text() = 'Surat Kuasa*'])[4]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>01ba3052-08e7-4c6f-8563-d0ea60bca9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>p3iIos1-real</value>
      <webElementGuid>f8f5a8f9-9814-4798-ae25-4c77a381db6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p3iIos1-cnt</value>
      <webElementGuid>fb736643-166d-4284-a8af-08e6d10d7492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>32ae322c-2a70-4992-9d20-1e9ddb186e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Surat Kuasa*</value>
      <webElementGuid>74ebd06c-32af-4282-85a3-02c6ac908df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p3iIos1-cnt&quot;)</value>
      <webElementGuid>97ad5fbf-9def-4b65-b668-d300615217f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='p3iIos1-cnt']</value>
      <webElementGuid>e7010584-45c1-437c-a79b-cb4797dbdbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='p3iIos1']/label</value>
      <webElementGuid>d508685c-bca6-47f5-bbd9-e3de1ab62f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan*'])[1]/following::label[2]</value>
      <webElementGuid>0d1a78f9-42cb-4eac-8d9a-68604680cc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penagihan yang Diadukan (Jika Ada)'])[1]/preceding::label[1]</value>
      <webElementGuid>5e60015f-6017-4af4-bb9e-b14fac105d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada dokumen'])[1]/preceding::label[2]</value>
      <webElementGuid>65b2ada2-fa62-47ae-8102-9255adde80e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Surat Kuasa*']/parent::*</value>
      <webElementGuid>fc47ed09-cd15-43f7-882f-6c6f59044c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/label</value>
      <webElementGuid>cd6e8fc0-98ee-4985-94e8-b555040653bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'p3iIos1-cnt' and (text() = 'Surat Kuasa*' or . = 'Surat Kuasa*')]</value>
      <webElementGuid>6782e939-3302-499b-91a7-e193e0c09b9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
